IMAGE=grim.dll
FUNCTION=grim_jpeg_request_virt_barray
SYMBOL=request_virt_barray
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jmemmgr.c
NOTE=ijg-6a-stock-memory-request-virtual-block-array
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
