IMAGE=grim.dll
FUNCTION=0x10025aec
COMPILER=msvc7.0
SYMBOL=crc32
SOURCE=../../../../third_party/sources/zlib-1.1.3/crc32.c
NOTE=zlib-1.1.3-d3dx-crc32
CFLAGS='/O1 /G6 /W3 /MD'
REFERENCE_ALIASES='crc_table:d3dx_zlib_crc_table'
RECOVERY=semantic-complete
RESIDUAL=compiler
