IMAGE=grim.dll
FUNCTION=jpeg_finish_decompress
SYMBOL=jpeg_finish_decompress
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdapimin.c
NOTE=ijg-6a-stock-finish-decompress
CFLAGS='/O2 /GB /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
