IMAGE=crimsonland.exe
FUNCTION=mod_api_gfx_set_texture_filter
SYMBOL=?mod_api_gfx_set_texture_filter@mod_api_cpp_t@@UAEXH@Z
SOURCE=../../../../decomp/1.9/crimsonland/mods/mod_api_gfx_set_texture_filter.cpp
NOTE=mod-api-graphics-texture-filter
