IMAGE=grim.dll
FUNCTION=d3dx_jpeg_prepare_range_limit_table
COMPILER=msvc7.0
SYMBOL=prepare_range_limit_table
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmaster.c
NOTE=ijg-6a-d3dx-range-limit-table-builder
CFLAGS='/O1 /Oi /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
