IMAGE=grim.dll
FUNCTION=grim_jpeg_realize_virt_arrays
SYMBOL=realize_virt_arrays
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jmemmgr.c
NOTE=ijg-6a-stock-memory-realize-virtual-arrays
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
