IMAGE=grim.dll
FUNCTION=d3dx_png_format_buffer
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\pngerror.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?png_format_buffer@D3DX@@YAXPAUpng_struct_def@1@PADPBD@Z'
NOTE=directx-8.1-archive-libpng-1.0.5-format-buffer
