IMAGE=grim.dll
FUNCTION=0x10032297
COMPILER=msvc7.0
SYMBOL=grim_jpeg_h2v2_merged_upsample
SOURCE=../../shared/grim_jpeg_merged_source.c
NOTE=ijg-merged-horizontal-and-vertical-two-to-one-color-converter
CFLAGS="/O1 /G6 /W3 /GR- /MD"
