IMAGE=grim.dll
FUNCTION=zlib_compress_block
SYMBOL=compress_block
SOURCE=../../../../third_party/sources/zlib-1.1.3/trees.c
NOTE=zlib-1.1.3-stock-compress-block
CFLAGS='/O2 /GB /W3 /MD'
REFERENCE_ALIASES='length_code:zlib_length_code,extra_lbits:zlib_extra_literal_bits,base_length:zlib_base_length,dist_code:zlib_distance_code,extra_dbits:zlib_extra_distance_bits,base_dist:zlib_base_distance'
