IMAGE=grim.dll
FUNCTION=grim_jpeg_process_data_crank_post
SYMBOL=process_data_crank_post
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmainct.c
NOTE=ijg-6a-stock-main-controller-crank-post
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
