IMAGE=grim.dll
FUNCTION=zlib_fill_window
SYMBOL=fill_window
SOURCE=../../../../third_party/sources/zlib-1.1.3/deflate.c
NOTE=zlib-1.1.3-stock-fill-window
CFLAGS='/O2 /Ob2 /GB /W3 /MD'
REFERENCE_ALIASES='adler32:zlib_adler32'
