IMAGE=grim.dll
FUNCTION=0x1003ac00
SYMBOL=format_message
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jerror.c
NOTE=ijg-6a-stock-format-message
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
