IMAGE=grim.dll
FUNCTION=d3dx_jpeg_set_bottom_pointers
COMPILER=msvc7.0
SYMBOL=set_bottom_pointers
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmainct.c
NOTE=ijg-6a-d3dx-context-bottom-pointer-setup
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
