IMAGE=grim.dll
FUNCTION=d3dx_jpeg_h2v2_fancy_upsample
COMPILER=msvc7.0
SYMBOL=h2v2_fancy_upsample
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdsample.c
NOTE=ijg-6a-d3dx-h2v2-fancy-upsampler
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
