IMAGE=crimsonland.exe
FUNCTION=crt_sopen
ARCHIVE=../../../native/providers/build/vc6-sp6/vc98/lib/libcmt.lib
ARCHIVE_MEMBER='build\intel\mt_obj\open.obj'
ARCHIVE_SHA256=a541c95e5ffdd6d5573d1976f5e5d0038f2c4fb0bcb02975c68948bf1d6e452a
SYMBOL=__sopen
REFERENCE_ALIASES=___doserrno:crt_doserrno_ptr,___pioinfo:crt_pioinfo_table,__chsize_lk:crt_chsize,__close:crt_close,__dosmaperr:crt_dosmaperr,__errno:crt_errno_ptr,__lseek_lk:crt_lseek_nolock,__read_lk:crt_read_nolock,__set_osfhnd:FUN_0046abbb,__unlock_fhandle:crt_unlock_fh
NOTE=vc6-sp6-libcmt-crt-sopen
