IMAGE=grim.dll
FUNCTION=x3d_quaternion_rotation_matrix
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='objd\i386\x3d_quat.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?x3d_D3DXQuaternionRotationMatrix@@YGPAUD3DXQUATERNION@@PAU1@PBUD3DXMATRIX@@@Z'
NOTE=directx-8.1-archive-x3d-quaternion-rotation-matrix
