IMAGE=grim.dll
FUNCTION=msvc_array_unwind
ARCHIVE=../../../native/providers/build/vc6-sp6/vc98/lib/libcmt.lib
ARCHIVE_MEMBER='build\intel\mt_obj\ehvecdtr.obj'
ARCHIVE_SHA256=a541c95e5ffdd6d5573d1976f5e5d0038f2c4fb0bcb02975c68948bf1d6e452a
SYMBOL='?__ArrayUnwind@@YGXPAXIHP6EX0@Z@Z'
REFERENCE_ALIASES='$T16560:msvc_array_unwind_scope_table'
NOTE=vc6-sp6-libcmt-array-unwind
