IMAGE=grim.dll
FUNCTION=png_read_finish_row
COMPILER=msvc7.0
SYMBOL=png_read_finish_row
SOURCE=../../../../third_party/sources/libpng-1.0.5/pngrutil.c
NOTE=libpng-1.0.5-read-finish-row
CFLAGS='/O1 /Oi /G6 /W3 /MD /DPNG_NO_READ_USER_TRANSFORM /DPNG_NO_WRITE_USER_TRANSFORM /DPNG_NO_READ_GRAY_TO_RGB /DPNG_NO_READ_BACKGROUND /DPNG_NO_READ_bKGD /DPNG_NO_READ_sBIT /DPNG_NO_READ_cHRM /DPNG_NO_CONSOLE_IO /DPNG_NO_READ_PACKSWAP'
