IMAGE=crimsonland.exe
FUNCTION=console_command_unregister
SYMBOL=?console_command_unregister@console_queue_t@@QAEEPAD@Z
SOURCE=../../../../decomp/1.9/crimsonland/console/console_command_unregister.cpp
NOTE=console-command-unlink
