IMAGE=grim.dll
FUNCTION=zlib_inflate_trees_bits
SYMBOL=inflate_trees_bits
SOURCE=../../../../third_party/sources/zlib-1.1.3/inftrees.c
NOTE=zlib-1.1.3-stock-inflate-trees-bits
CFLAGS='/O2 /GB /W3 /MD'
REFERENCE_ALIASES='huft_build:zlib_huft_build'
