IMAGE=grim.dll
FUNCTION=d3dx_jpeg_use_merged_upsample
COMPILER=msvc7.0
SYMBOL=use_merged_upsample
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmaster.c
NOTE=ijg-6a-d3dx-merged-upsample-predicate
CFLAGS='/O1 /Oi /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
