IMAGE=crimsonland.exe
FUNCTION=game_status_global_init
SYMBOL=game_status_global_init
SOURCE=../../../../decomp/1.9/crimsonland/gameplay/game_status_global_init.cpp
NOTE=game-status-global-constructor
