IMAGE=grim.dll
FUNCTION=d3dx_jpeg_alloc_funny_pointers
COMPILER=msvc7.0
SYMBOL=alloc_funny_pointers
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmainct.c
NOTE=ijg-6a-d3dx-context-pointer-list-allocation
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='alloc_small:d3dx_jpeg_alloc_small'
