IMAGE=grim.dll
FUNCTION=grim_jpeg_ycc_rgb_convert
SYMBOL=ycc_rgb_convert
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdcolor.c
NOTE=ijg-6a-stock-ycc-rgb-converter
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
