IMAGE=grim.dll
FUNCTION=grim_jpeg_alloc_huff_table
SYMBOL=jpeg_alloc_huff_table
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jcomapi.c
NOTE=ijg-6a-stock-alloc-huff-table
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
