IMAGE=grim.dll
FUNCTION=grim_jpeg_get_sof
SYMBOL=get_sof
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmarker.c
NOTE=ijg-6a-stock-get-sof
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
