IMAGE=grim.dll
FUNCTION=d3dx_jpeg_init_d_post_controller
COMPILER=msvc7.0
SYMBOL=jinit_d_post_controller
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdpostct.c
NOTE=ijg-6a-d3dx-postprocessor-controller-init
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='start_pass_dpost:d3dx_jpeg_start_pass_dpost'
