IMAGE=crimsonland.exe
FUNCTION=render_tint_color_global_init_thunk
SYMBOL=render_tint_color_global_init_thunk
SOURCE=../../../../decomp/1.9/crimsonland/crimsonland/render_tint_color_global_init_thunk.cpp
NOTE=render-tint-color-global-init-thunk
