IMAGE=crimsonland.exe
FUNCTION=console_log_node_free
SYMBOL='?release@console_log_node_t@@QAEPAU1@E@Z'
SOURCE=../../../../decomp/1.9/crimsonland/console/console_log_node_free.cpp
NOTE=console-log-node-destructor
