IMAGE=crimsonland.exe
FUNCTION=input_detect_active_analog_axis
SYMBOL=input_detect_active_analog_axis
SOURCE=../../../../decomp/1.9/crimsonland/menus/input_detect_active_analog_axis.cpp
CFLAGS="/O2 /GB /W3 /GR-"
NOTE=input-analog-axis-detection
