IMAGE=grim.dll
FUNCTION=d3dx_jpeg_idct_4x4
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\jidctred.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?jpeg_idct_4x4@D3DX@@YAXPAUjpeg_decompress_struct@1@PAUjpeg_component_info@1@PAFPAPAEI@Z'
NOTE=directx-8.1-archive-d3dx-jpeg-idct-4x4
