IMAGE=grim.dll
FUNCTION=d3dx_jpeg_null_convert
COMPILER=msvc7.0
SYMBOL=null_convert
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdcolor.c
NOTE=ijg-6a-d3dx-null-color-converter
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
