IMAGE=grim.dll
FUNCTION=0x1003196a
COMPILER=msvc7.0
SYMBOL=grim_jpeg_null_convert
SOURCE=../../shared/grim_jpeg_source_helpers.cpp
NOTE=ijg-planar-to-interleaved-null-color-converter
CFLAGS="/O1 /G6 /W3 /GR- /MD"
