IMAGE=grim.dll
FUNCTION=png_calculate_crc
COMPILER=msvc6.5
SYMBOL=grim_png_calculate_crc
SOURCE=../../shared/grim_png_callbacks.cpp
NOTE=png-conditional-crc-update
CFLAGS="/O1 /G6 /W3 /GR- /MD"
REFERENCE_ALIASES='grim_png_crc32:sub_10025AEC'
