IMAGE=grim.dll
FUNCTION=d3dx_jpeg_latch_quant_tables
COMPILER=msvc7.0
SYMBOL=latch_quant_tables
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdinput.c
NOTE=ijg-6a-d3dx-quantization-table-latch
CFLAGS='/O1 /Oi /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
