IMAGE=grim.dll
FUNCTION=grim_jpeg_skip_variable
SYMBOL=skip_variable
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmarker.c
NOTE=ijg-6a-stock-skip-variable
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
