IMAGE=grim.dll
FUNCTION=png_free_ptr
COMPILER=msvc6.5pp
SYMBOL=grim_png_free_ptr
SOURCE=../../shared/grim_png_callbacks.cpp
NOTE=png-default-free-callback
CFLAGS="/O1 /G6 /W3 /GR- /MD"
REFERENCE_ALIASES='free:free'
