IMAGE=crimsonland.exe
FUNCTION=mod_api_sfx_load_tune
SYMBOL=?mod_api_sfx_load_tune@mod_api_cpp_t@@UAEHPAD@Z
SOURCE=../../../../decomp/1.9/crimsonland/mods/mod_api_sfx_load_tune.cpp
NOTE=mod-api-audio-tune-load
