IMAGE=crimsonland.exe
FUNCTION=ui_menu_main_click_options
SYMBOL=ui_menu_main_click_options
SOURCE=../../../../decomp/1.9/crimsonland/ui_elements/ui_menu_main_click_options.cpp
NOTE=ui-menu-state-callback
