IMAGE=grim.dll
FUNCTION=zlib_inflate_end
SYMBOL=inflateEnd
SOURCE=../../../../third_party/sources/zlib-1.1.3/inflate.c
NOTE=zlib-1.1.3-stock-inflate-end
CFLAGS='/O2 /GB /W3 /MD'
REFERENCE_ALIASES='inflate_blocks_free:zlib_inflate_blocks_free'
