IMAGE=grim.dll
FUNCTION=d3dx_jpeg_decompress_data
COMPILER=msvc7.0
SYMBOL=decompress_data
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdcoefct.c
NOTE=ijg-6a-d3dx-coefficient-decompressor
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
