IMAGE=grim.dll
FUNCTION=grim_jpeg_prepare_for_output_pass
SYMBOL=prepare_for_output_pass
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmaster.c
NOTE=ijg-6a-stock-prepare-output-pass
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
