IMAGE=grim.dll
FUNCTION=grim_dxt_unpremultiply_rgba_block
SYMBOL='@grim_dxt_unpremultiply_rgba_block@4'
SOURCE=scratch.cpp
COMPILER=msvc6.5pp
CFLAGS="/O1 /Oi /G6 /W3 /GR-"
NOTE=grim-dxt-unpremultiply-rgba-block
