IMAGE=grim.dll
FUNCTION=d3dx_jpeg_alloc_small
COMPILER=msvc7.0
SYMBOL=alloc_small
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jmemmgr.c
NOTE=ijg-6a-d3dx-small-object-pool-allocator
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='out_of_memory:d3dx_jpeg_out_of_memory,first_pool_slop:d3dx_jpeg_first_pool_slop,extra_pool_slop:d3dx_jpeg_extra_pool_slop,jpeg_get_small:d3dx_jpeg_get_small'
