IMAGE=grim.dll
FUNCTION=x3d_log
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='.\Release\math.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='_a_log'
REFERENCE_ALIASES='mant:d3dx_x87_math_mantissa_mask,expo:d3dx_x87_math_exponent_mask,one:d3dx_x87_math_one,rt2:d3dx_x87_math_root_two,edec:d3dx_x87_math_exponent_decrement,bias:d3dx_x87_math_exponent_bias,ln2lo:d3dx_x87_math_ln2_low,ln2hi:d3dx_x87_math_ln2_high,c2:d3dx_x87_math_log_c2,c1:d3dx_x87_math_log_c1,c0:d3dx_x87_math_log_c0,maxn:d3dx_x87_math_max_normal'
NOTE=directx-8.1-archive-x87-log
