IMAGE=crimsonland.exe
FUNCTION=mod_api_core_del_var
SYMBOL=?mod_api_core_del_var@mod_api_cpp_t@@UAEEPAD@Z
SOURCE=../../../../decomp/1.9/crimsonland/mods/mod_api_core_del_var.cpp
NOTE=mod-api-core-cvar-delete
