pub const Caller = enum(u32) {
    bonus_pick_random_type_roll = 0x004124A5,
    bonus_pick_random_type_energizer = 0x004124D6,
    bonus_spawn_at_pos_points_amount = 0x0041F897,
    bonus_apply_nuke_bullet_count = 0x0040A00B,
    bonus_apply_nuke_pistol_angle = 0x0040A023,
    bonus_apply_nuke_pistol_speed_scale = 0x0040A059,
    bonus_apply_nuke_gauss_angle_1 = 0x0040A088,
    bonus_apply_nuke_gauss_angle_2 = 0x0040A0B4,
    bonus_apply_pickup_burst_rotation = 0x0040A29A,
    bonus_apply_pickup_burst_vel_x = 0x0040A2B6,
    bonus_apply_pickup_burst_vel_y = 0x0040A2D8,
    bonus_try_spawn_on_kill_pistol_force_weapon = 0x0041F92C,
    bonus_try_spawn_on_kill_base_gate = 0x0041F9AA,
    bonus_try_spawn_on_kill_pistol_allow_without_magnet = 0x0041F9C3,
    bonus_try_spawn_on_kill_bonus_magnet = 0x0041F9EB,
    bonus_try_spawn_on_kill_burst_rotation = 0x0041FB0F,
    bonus_try_spawn_on_kill_burst_vel_x = 0x0041FB2B,
    bonus_try_spawn_on_kill_burst_vel_y = 0x0041FB4D,
    bonus_try_spawn_on_kill_burst_scale_step = 0x0041FB6F,
    player_update_low_health_bloodspill = 0x0041381C,
    player_update_casing_angle = 0x00415A6D,
    player_update_casing_speed = 0x00415A8B,
    player_update_casing_rotation = 0x00415B26,
    player_update_casing_rotation_step = 0x00415B79,
    player_update_shot_jitter_dir = 0x00415C6B,
    player_update_shot_jitter_mag = 0x00415C87,
    player_update_fire_bullets_pellet_jitter = 0x00415DAD,
    player_update_shot_sfx = 0x00415F09,
    player_update_shotgun_pellet_jitter = 0x00416364,
    player_update_shotgun_pellet_speed_scale = 0x00416399,
    player_update_sawed_off_shotgun_pellet_jitter = 0x00416478,
    player_update_sawed_off_shotgun_pellet_speed_scale = 0x004164AD,
    player_update_jackhammer_pellet_jitter = 0x004165FE,
    player_update_jackhammer_pellet_speed_scale = 0x00416633,
    player_update_ion_shotgun_pellet_jitter = 0x00416B44,
    player_update_ion_shotgun_pellet_speed_scale = 0x00416B79,
    player_update_gauss_shotgun_pellet_jitter = 0x00416CFD,
    player_update_gauss_shotgun_pellet_speed_scale = 0x00416D32,
    player_update_plasma_shotgun_pellet_jitter = 0x0041735A,
    player_update_plasma_shotgun_pellet_speed_scale = 0x0041738E,
    player_update_fire_cough_spread_dir = 0x00413B16,
    player_update_fire_cough_spread_mag = 0x00413B32,
    player_update_fire_cough_interval_reset = 0x00413C4F,
    player_update_hot_tempered_interval_reset = 0x00413D3A,
    player_update_man_bomb_ion_rifle_angle = 0x00413924,
    player_update_man_bomb_ion_minigun_angle = 0x0041393D,
    creature_alloc_slot_phase_seed = 0x004281A2,
    survival_spawn_creature_type_roll = 0x0040754B,
    survival_spawn_creature_parity_pick = 0x004075B8,
    survival_spawn_creature_rare_override = 0x00407616,
    survival_spawn_creature_size = 0x00407625,
    survival_spawn_creature_heading = 0x0040766C,
    survival_spawn_creature_health = 0x004076D9,
    survival_spawn_creature_low_tint_g = 0x00407792,
    survival_spawn_creature_low_tint_b = 0x004077E3,
    survival_spawn_creature_mid_tint_g = 0x00407848,
    survival_spawn_creature_mid_tint_b = 0x00407899,
    survival_spawn_creature_high_tint_g = 0x00407906,
    survival_spawn_creature_high_tint_b = 0x00407957,
    survival_spawn_creature_reward_bonus = 0x004079CF,
    survival_spawn_creature_rare_red = 0x00407A0A,
    survival_spawn_creature_rare_green = 0x00407A6C,
    survival_spawn_creature_rare_blue = 0x00407ACB,
    survival_spawn_creature_rare_purple = 0x00407B28,
    survival_spawn_creature_rare_yellow = 0x00407B93,
    survival_update_extra_spawn_edge = 0x00408338,
    survival_update_extra_spawn_top_x = 0x00408356,
    survival_update_extra_spawn_bottom_x = 0x00408381,
    survival_update_extra_spawn_left_y = 0x004083B2,
    survival_update_extra_spawn_right_y = 0x004083DB,
    survival_update_main_spawn_edge = 0x00408423,
    survival_update_main_spawn_top_x = 0x00408441,
    survival_update_main_spawn_bottom_x = 0x0040846C,
    survival_update_main_spawn_left_y = 0x0040849D,
    survival_update_main_spawn_right_y = 0x004084C6,
    creature_spawn_heading = 0x004282DC,
    creature_spawn_reward = 0x00428315,
    creature_handle_death_split_child_1_phase_seed = 0x0041E9F4,
    creature_handle_death_split_child_2_phase_seed = 0x0041EA91,
    creature_handle_death_freeze_shard_angle = 0x0041EBEA,
    creature_handle_death_freeze_shatter_angle = 0x0041EC15,
    creature_spawn_template_random_heading = 0x00430B14,
    creature_spawn_template_base_heading = 0x00430B88,
    creature_spawn_template_ai1_blue_tint_1a = 0x004323EC,
    creature_spawn_template_ai1_blue_tint_1b = 0x00432440,
    creature_spawn_template_ai1_blue_tint_1c = 0x0043248B,
    creature_spawn_template_alien_random_1d_size = 0x0043303B,
    creature_spawn_template_alien_random_1d_move_speed = 0x00433065,
    creature_spawn_template_alien_random_1d_reward = 0x00433089,
    creature_spawn_template_alien_random_1d_tint_r = 0x004330AB,
    creature_spawn_template_alien_random_1d_tint_g = 0x004330CF,
    creature_spawn_template_alien_random_1d_tint_b = 0x004330F3,
    creature_spawn_template_alien_random_1d_contact_damage = 0x00433117,
    creature_spawn_template_alien_random_1e_size = 0x0043314A,
    creature_spawn_template_alien_random_1e_move_speed = 0x00433174,
    creature_spawn_template_alien_random_1e_reward = 0x00433198,
    creature_spawn_template_alien_random_1e_tint_r = 0x004331BA,
    creature_spawn_template_alien_random_1e_tint_g = 0x004331DE,
    creature_spawn_template_alien_random_1e_tint_b = 0x00433202,
    creature_spawn_template_alien_random_1e_contact_damage = 0x00433226,
    creature_spawn_template_alien_random_1f_size = 0x00433259,
    creature_spawn_template_alien_random_1f_move_speed = 0x00433283,
    creature_spawn_template_alien_random_1f_reward = 0x004332A7,
    creature_spawn_template_alien_random_1f_tint_r = 0x004332C9,
    creature_spawn_template_alien_random_1f_tint_g = 0x004332ED,
    creature_spawn_template_alien_random_1f_tint_b = 0x00433311,
    creature_spawn_template_alien_random_1f_contact_damage = 0x00433335,
    creature_spawn_template_alien_random_green_20_size = 0x00432857,
    creature_spawn_template_alien_random_green_20_move_speed = 0x00432881,
    creature_spawn_template_alien_random_green_20_tint_g = 0x004328C2,
    creature_spawn_template_alien_random_green_20_contact_damage = 0x004328E9,
    creature_spawn_template_spider_sp1_random_03_size = 0x0043291C,
    creature_spawn_template_spider_sp1_random_03_move_speed = 0x00432946,
    creature_spawn_template_spider_sp1_random_03_tint_b = 0x0043298B,
    creature_spawn_template_spider_sp1_random_03_contact_damage = 0x00432A4F,
    creature_spawn_template_spider_sp2_random_05_size = 0x00432A82,
    creature_spawn_template_spider_sp2_random_05_move_speed = 0x00432AAC,
    creature_spawn_template_spider_sp2_random_05_tint_b = 0x00432AF1,
    creature_spawn_template_spider_sp2_random_05_contact_damage = 0x00432BB5,
    creature_spawn_template_lizard_random_04_size = 0x00432BE8,
    creature_spawn_template_lizard_random_04_move_speed = 0x00432C12,
    creature_spawn_template_lizard_random_04_contact_damage = 0x00432C5A,
    creature_spawn_template_alien_random_06_size = 0x00432C8D,
    creature_spawn_template_alien_random_06_move_speed = 0x00432CB7,
    creature_spawn_template_alien_random_06_tint_b = 0x00432CFC,
    creature_spawn_template_alien_random_06_contact_damage = 0x00432DC0,
    creature_spawn_template_lizard_random_31_size = 0x00432579,
    creature_spawn_template_lizard_random_31_move_speed = 0x004325A3,
    creature_spawn_template_lizard_random_31_tint = 0x004325DC,
    creature_spawn_template_spider_sp1_random_32_size = 0x0043261F,
    creature_spawn_template_spider_sp1_random_32_move_speed = 0x00432643,
    creature_spawn_template_spider_sp1_random_32_tint = 0x0043267C,
    creature_spawn_template_spider_sp1_random_red_33_size = 0x004326CD,
    creature_spawn_template_spider_sp1_random_red_33_move_speed = 0x004326F7,
    creature_spawn_template_spider_sp1_random_red_33_tint_r = 0x00432730,
    creature_spawn_template_spider_sp1_random_red_33_contact_damage = 0x0043275F,
    creature_spawn_template_spider_sp1_random_green_34_size = 0x00432792,
    creature_spawn_template_spider_sp1_random_green_34_move_speed = 0x004327BC,
    creature_spawn_template_spider_sp1_random_green_34_tint_g = 0x004327F5,
    creature_spawn_template_spider_sp1_random_green_34_contact_damage = 0x00432824,
    creature_spawn_template_lizard_random_2e_size = 0x00432EB8,
    creature_spawn_template_lizard_random_2e_move_speed = 0x00432EE2,
    creature_spawn_template_lizard_random_2e_tint_r = 0x00432F1B,
    creature_spawn_template_lizard_random_2e_tint_g = 0x00432F3F,
    creature_spawn_template_lizard_random_2e_tint_b = 0x00432F63,
    creature_spawn_template_lizard_random_2e_contact_damage = 0x00432F87,
    creature_spawn_template_spider_sp2_random_35_size = 0x00432DF3,
    creature_spawn_template_spider_sp2_random_35_move_speed = 0x00432E1D,
    creature_spawn_template_spider_sp2_random_35_tint_g = 0x00432E5E,
    creature_spawn_template_spider_sp2_random_35_contact_damage = 0x00432E85,
    creature_spawn_template_ai7_orbiter_tint_g = 0x00432FED,
    creature_spawn_template_spider_sp1_random_3d_tint = 0x00433B39,
    creature_spawn_template_spider_sp1_random_3d_size = 0x00433B63,
    creature_spawn_template_spider_sp1_ai7_timer_38_size = 0x00433D18,
    creature_spawn_template_spider_sp2_ranged_variant_37_size = 0x00433DB3,
    creature_spawn_template_spider_sp1_ai7_timer_weak_39_size = 0x00433E4E,
    creature_spawn_template_zombie_random_41_size = 0x004324CD,
    creature_spawn_template_zombie_random_41_tint = 0x0043251C,
    creature_spawn_template_zombie_random_41_contact_damage = 0x00432546,
    creature_update_all_ai7_link_timer_hold = 0x00426381,
    creature_update_all_ai7_link_timer_reset = 0x004263B1,
    creature_update_all_contact_sfx = 0x00427273,
    creature_update_all_plasmaminigun_cooldown = 0x00427119,
    creature_update_all_plague_kill_sfx = 0x00426611,
    creature_update_all_ping_pong_blood_8_angle = 0x004275A3,
    creature_update_all_ping_pong_blood_6_angle = 0x004275D8,
    creature_update_all_ping_pong_blood_5_angle = 0x0042760D,
    creature_apply_damage_heading_jitter = 0x004208A9,
    creature_apply_damage_pyromaniac = 0x0042092D,
    creature_apply_damage_death_sfx = 0x00420B16,
    creature_apply_damage_shock_burst_rotation = 0x00420A4B,
    creature_apply_damage_shock_burst_vel_x = 0x00420A67,
    creature_apply_damage_shock_burst_vel_y = 0x00420A80,
    creature_apply_damage_shock_burst_scale_step = 0x00420A99,
    bonus_apply_freeze_shard_angle = 0x00409BDC,
    bonus_apply_freeze_shatter_angle = 0x00409C07,
    projectile_update_poison_bullets_gate = 0x00420E84,
    projectile_update_blade_gun_splatter_angle = 0x00420EAF,
    projectile_update_bloody_mess_spread = 0x00420FD7,
    projectile_update_default_reverse_splatter_gate = 0x0042105B,
    projectile_update_bloody_mess_decal_dx_1 = 0x004210D3,
    projectile_update_bloody_mess_decal_dy_1 = 0x004210EE,
    projectile_update_bloody_mess_decal_dx_2 = 0x00421130,
    projectile_update_bloody_mess_decal_dy_2 = 0x0042114B,
    projectile_update_stop_on_hit_jitter = 0x004211C4,
    projectile_update_post_hit_decal_burn = 0x004215D2,
    projectile_update_default_freeze_shard_angle = 0x004215FF,
    projectile_update_decal_spread = 0x00421642,
    projectile_update_large_streak_dist = 0x0042176F,
    projectile_update_large_streak_dist_gt4 = 0x00421799,
    projectile_update_large_streak_dist_gt7 = 0x004217C6,
    projectile_update_large_streak_burn = 0x0042184C,
    projectile_update_large_streak_freeze_angle = 0x00421879,
    projectile_update_hit_sfx = 0x00421936,
    projectile_update_particle_jitter_flamethrower = 0x0042277A,
    projectile_update_particle_jitter_bubblegun = 0x004227AE,
    projectile_update_particle_jitter_alt = 0x004227F9,
    projectile_update_particle_bounce_speed_scale = 0x00422A01,
    projectile_update_particle_sprite_vel_x = 0x00422BA8,
    projectile_update_particle_sprite_vel_y = 0x00422BBC,
    secondary_projectile_update_pre_hit_decal_dx_1 = 0x00421EEB,
    secondary_projectile_update_pre_hit_decal_dy_1 = 0x00421F0A,
    secondary_projectile_update_pre_hit_decal_dx_2 = 0x00421F47,
    secondary_projectile_update_pre_hit_decal_dy_2 = 0x00421F66,
    secondary_projectile_update_pre_hit_decal_dx_3 = 0x00421FAC,
    secondary_projectile_update_pre_hit_decal_dy_3 = 0x00421FCB,
    secondary_projectile_update_pre_hit_freeze_shard_angle = 0x00421EB3,
    secondary_projectile_update_rocket_freeze_shard_angle = 0x00422130,
    secondary_projectile_update_rocket_decal_angle = 0x00422165,
    secondary_projectile_update_rocket_decal_radius = 0x00422184,
    secondary_projectile_update_seeker_rocket_freeze_shard_angle = 0x0042221E,
    secondary_projectile_update_seeker_rocket_decal_angle = 0x00422253,
    secondary_projectile_update_seeker_rocket_decal_radius = 0x00422272,
    secondary_projectile_update_rocket_minigun_freeze_shard_angle = 0x0042230D,
    secondary_projectile_update_rocket_minigun_decal_angle = 0x0042233F,
    secondary_projectile_update_rocket_minigun_decal_radius = 0x0042235E,
    secondary_projectile_update_detonation_sprite_mag = 0x004223BE,
    unlock_terrain_q4 = 0x00418229,
    unlock_terrain_q3 = 0x00418254,
    unlock_terrain_q2 = 0x0041827F,
    terrain_generate_random_prelude_1 = 0x004181CC,
    terrain_generate_random_prelude_2 = 0x004181DF,
    terrain_generate_random_prelude_3 = 0x004181F2,
    terrain_generate_random_base_rotation = 0x004183FC,
    terrain_generate_random_base_y = 0x00418427,
    terrain_generate_random_base_x = 0x0041844D,
    terrain_generate_random_overlay_rotation = 0x00418559,
    terrain_generate_random_overlay_y = 0x00418584,
    terrain_generate_random_overlay_x = 0x004185AA,
    terrain_generate_random_detail_rotation = 0x004186B6,
    terrain_generate_random_detail_y = 0x004186E1,
    terrain_generate_random_detail_x = 0x00418707,
    terrain_generate_base_rotation = 0x00417D22,
    terrain_generate_base_y = 0x00417D4D,
    terrain_generate_base_x = 0x00417D73,
    terrain_generate_overlay_rotation = 0x00417E88,
    terrain_generate_overlay_y = 0x00417EB3,
    terrain_generate_overlay_x = 0x00417ED9,
    terrain_generate_detail_rotation = 0x00417FEB,
    terrain_generate_detail_y = 0x00418016,
    terrain_generate_detail_x = 0x0041803C,
    player_take_damage_ninja = 0x00425F23,
    player_take_damage_dodger = 0x00425F4E,
    player_take_damage_highlander = 0x00425F79,
    player_take_damage_death_sfx = 0x00426124,
    player_take_damage_pain_sfx = 0x00426152,
    player_take_damage_heading = 0x00426197,
    player_take_damage_low_health = 0x00426201,
    fx_queue_add_random_gray = 0x00427760,
    fx_queue_add_random_width = 0x0042778E,
    fx_queue_add_random_rotation = 0x004277B0,
    fx_queue_add_random_effect_id = 0x0042780B,
    fx_spawn_particle_alloc = 0x00420151,
    fx_spawn_particle_spin = 0x00420206,
    fx_spawn_particle_slow_alloc = 0x00420261,
    fx_spawn_particle_slow_spin = 0x00420316,
    fx_spawn_sprite_alloc = 0x0041FBCE,
    fx_spawn_sprite_rotation = 0x0041FC3E,
    effect_spawn_blood_splatter_rotation = 0x0042EBC0,
    effect_spawn_blood_splatter_half = 0x0042EBE3,
    effect_spawn_blood_splatter_speed_x = 0x0042EC00,
    effect_spawn_blood_splatter_speed_y = 0x0042EC1D,
    effect_spawn_blood_splatter_scale_step = 0x0042EC44,
    effect_spawn_burst_rotation = 0x0042EFF2,
    effect_spawn_burst_vel_x = 0x0042F00E,
    effect_spawn_burst_vel_y = 0x0042F027,
    effect_spawn_burst_scale_step = 0x0042F040,
    effect_spawn_freeze_shard_lifetime = 0x0042ECD8,
    effect_spawn_freeze_shard_rotation = 0x0042ED26,
    effect_spawn_freeze_shard_half = 0x0042ED4B,
    effect_spawn_freeze_shard_rotation_step = 0x0042ED93,
    effect_spawn_freeze_shard_scale_step = 0x0042EDC0,
    effect_spawn_freeze_shard_effect_id = 0x0042EDE3,
    effect_spawn_freeze_shatter_half = 0x0042EEB8,
    effect_spawn_freeze_shatter_rotation_step = 0x0042EEDC,
    effect_spawn_freeze_shatter_shard_angle = 0x0042EF27,
    effect_spawn_explosion_burst_puff_rotation = 0x0042F848,
    effect_spawn_explosion_burst_rotation = 0x0042F9E6,
    effect_spawn_explosion_burst_vel_x = 0x0042FA07,
    effect_spawn_explosion_burst_vel_y = 0x0042FA21,
    effect_spawn_explosion_burst_scale_step = 0x0042FA3B,
    effect_spawn_explosion_burst_rotation_step = 0x0042FA58,
    perk_select_random = 0x0042FBDC,
    perks_generate_choices_rarity_gate = 0x004046D4,
    perk_apply_fatal_lottery = 0x0040562F,
    perk_apply_bandage_heal = 0x004058C9,
    perks_update_effects_regeneration_gate = 0x00406B62,
    perks_update_effects_pyrokinetic_angle_0p8 = 0x00406DFF,
    perks_update_effects_pyrokinetic_angle_0p6 = 0x00406E41,
    perks_update_effects_pyrokinetic_angle_0p4 = 0x00406E83,
    perks_update_effects_pyrokinetic_angle_0p3 = 0x00406EC5,
    perks_update_effects_pyrokinetic_angle_0p2 = 0x00406F07,
    perks_update_effects_jinxed_accident_gate = 0x00406FB4,
    perks_update_effects_jinxed_timer_reset = 0x00406FEF,
    perks_update_effects_jinxed_creature_pick = 0x00407033,
    perks_update_effects_jinxed_creature_retry = 0x00407055,
    quest_start_selected_highscore_random_tag = 0x0043A81B,
    quest_build_target_practice_angle = 0x00437A19,
    quest_build_target_practice_radius = 0x00437A38,
    quest_build_the_random_factor_brute_gate = 0x004363DF,
    quest_build_sweep_stakes_angle = 0x00437838,
    quest_build_deja_vu_angle = 0x00437946,
    quest_build_the_killing_template_pick = 0x004384BE,
    quest_build_the_killing_layout_pick = 0x004384F0,
    quest_build_the_killing_spawner_1_y = 0x004385D7,
    quest_build_the_killing_spawner_1_x = 0x004385F5,
    quest_build_the_killing_spawner_2_y = 0x00438628,
    quest_build_the_killing_spawner_2_x = 0x00438646,
    quest_build_the_killing_spawner_3_y = 0x0043867F,
    quest_build_the_killing_spawner_3_x = 0x0043869D,
    typo_word_pick_fragment = 0x00444F88,
    typo_word_pick_highscore_name = 0x004452EB,
    typo_target_name_assign_random_highscore_gate = 0x004453A8,
    typo_target_name_assign_random_four_word_gate = 0x004453F6,
    typo_target_name_assign_random_three_word_gate_gt80 = 0x0044545B,
    typo_target_name_assign_random_three_word_gate_gt60 = 0x004454B5,
    typo_target_name_assign_random_two_word_gate_gt40 = 0x004454D0,
    typo_target_name_assign_random_two_word_gate_gt20 = 0x0044551C,
    typo_gameplay_typeclick_backspace = 0x0044593F,
    typo_gameplay_typeclick_char = 0x004459A1,
    creature_spawn_tinted_heading = 0x004448A3,
    creature_spawn_tinted_size = 0x004448FE,
    ui_text_input_update_typeclick = 0x0043EDC2,
    credits_secret_alien_zookeeper_fill_empty = 0x0040FD61,
    credits_secret_alien_zookeeper_reroll_fill = 0x0040FE2C,
    sfx_play_exclusive_playlist_pick = 0x0043D4BD,
    camera_update_offset_x_base = 0x00409578,
    camera_update_offset_x_spread = 0x004095A7,
    camera_update_offset_x_sign = 0x004095BA,
    camera_update_offset_y_base = 0x004095D9,
    camera_update_offset_y_spread = 0x00409608,
    camera_update_offset_y_sign = 0x0040961B,
    demo_setup_variant_1_spider_sp1_x = 0x0040311C,
    demo_setup_variant_1_spider_sp1_y = 0x00403138,
    demo_setup_variant_1_spider_sp2_x = 0x0040317E,
    demo_setup_variant_1_spider_sp2_y = 0x0040319A,
    demo_setup_variant_3_alien_big_x = 0x0040327C,
    demo_setup_variant_3_alien_big_y = 0x00403298,
    demo_setup_variant_3_alien_small_x = 0x004032DB,
    demo_setup_variant_3_alien_small_y = 0x004032F7,
    shrinkifier_hit_rotation = 0x0042F1CE,
    shrinkifier_hit_vel_x = 0x0042F1EA,
    shrinkifier_hit_vel_y = 0x0042F209,
    shrinkifier_hit_scale_step = 0x0042F228,
    splitter_hit_angle = 0x0042F4A2,
    splitter_hit_radius = 0x0042F4C4,
    splitter_hit_age = 0x0042F4F3,
    ion_hit_spark_rotation = 0x0042F61A,
    ion_hit_spark_vel_x = 0x0042F636,
    ion_hit_spark_vel_y = 0x0042F659,
    ion_hit_spark_scale_step = 0x0042F67C,
    weapon_pick_random_available_pick = 0x00452CD6,
    weapon_pick_random_available_reroll_gate = 0x00452CF1,
    weapon_pick_random_available_reroll_pick = 0x00452CFA,
    rewrite_jinxed_accident_target_pick = 0xF1000001,
    game_frame_update_discarded = 0x0040CAC7,
    rewrite_stats_menu_easter_roll = 0xF1000006,
    rewrite_stats_menu_easter_text_x = 0xF1000007,
};

pub const bonus_pick_random_type_roll: Caller = .bonus_pick_random_type_roll;
pub const bonus_pick_random_type_energizer: Caller = .bonus_pick_random_type_energizer;
pub const bonus_spawn_at_pos_points_amount: Caller = .bonus_spawn_at_pos_points_amount;
pub const bonus_apply_nuke_bullet_count: Caller = .bonus_apply_nuke_bullet_count;
pub const bonus_apply_nuke_pistol_angle: Caller = .bonus_apply_nuke_pistol_angle;
pub const bonus_apply_nuke_pistol_speed_scale: Caller = .bonus_apply_nuke_pistol_speed_scale;
pub const bonus_apply_nuke_gauss_angle_1: Caller = .bonus_apply_nuke_gauss_angle_1;
pub const bonus_apply_nuke_gauss_angle_2: Caller = .bonus_apply_nuke_gauss_angle_2;
pub const bonus_apply_pickup_burst_rotation: Caller = .bonus_apply_pickup_burst_rotation;
pub const bonus_apply_pickup_burst_vel_x: Caller = .bonus_apply_pickup_burst_vel_x;
pub const bonus_apply_pickup_burst_vel_y: Caller = .bonus_apply_pickup_burst_vel_y;
pub const bonus_try_spawn_on_kill_pistol_force_weapon: Caller = .bonus_try_spawn_on_kill_pistol_force_weapon;
pub const bonus_try_spawn_on_kill_base_gate: Caller = .bonus_try_spawn_on_kill_base_gate;
pub const bonus_try_spawn_on_kill_pistol_allow_without_magnet: Caller = .bonus_try_spawn_on_kill_pistol_allow_without_magnet;
pub const bonus_try_spawn_on_kill_bonus_magnet: Caller = .bonus_try_spawn_on_kill_bonus_magnet;
pub const bonus_try_spawn_on_kill_burst_rotation: Caller = .bonus_try_spawn_on_kill_burst_rotation;
pub const bonus_try_spawn_on_kill_burst_vel_x: Caller = .bonus_try_spawn_on_kill_burst_vel_x;
pub const bonus_try_spawn_on_kill_burst_vel_y: Caller = .bonus_try_spawn_on_kill_burst_vel_y;
pub const bonus_try_spawn_on_kill_burst_scale_step: Caller = .bonus_try_spawn_on_kill_burst_scale_step;
pub const player_update_low_health_bloodspill: Caller = .player_update_low_health_bloodspill;
pub const player_update_casing_angle: Caller = .player_update_casing_angle;
pub const player_update_casing_speed: Caller = .player_update_casing_speed;
pub const player_update_casing_rotation: Caller = .player_update_casing_rotation;
pub const player_update_casing_rotation_step: Caller = .player_update_casing_rotation_step;
pub const player_update_shot_jitter_dir: Caller = .player_update_shot_jitter_dir;
pub const player_update_shot_jitter_mag: Caller = .player_update_shot_jitter_mag;
pub const player_update_fire_bullets_pellet_jitter: Caller = .player_update_fire_bullets_pellet_jitter;
pub const player_update_shot_sfx: Caller = .player_update_shot_sfx;
pub const player_update_shotgun_pellet_jitter: Caller = .player_update_shotgun_pellet_jitter;
pub const player_update_shotgun_pellet_speed_scale: Caller = .player_update_shotgun_pellet_speed_scale;
pub const player_update_sawed_off_shotgun_pellet_jitter: Caller = .player_update_sawed_off_shotgun_pellet_jitter;
pub const player_update_sawed_off_shotgun_pellet_speed_scale: Caller = .player_update_sawed_off_shotgun_pellet_speed_scale;
pub const player_update_jackhammer_pellet_jitter: Caller = .player_update_jackhammer_pellet_jitter;
pub const player_update_jackhammer_pellet_speed_scale: Caller = .player_update_jackhammer_pellet_speed_scale;
pub const player_update_ion_shotgun_pellet_jitter: Caller = .player_update_ion_shotgun_pellet_jitter;
pub const player_update_ion_shotgun_pellet_speed_scale: Caller = .player_update_ion_shotgun_pellet_speed_scale;
pub const player_update_gauss_shotgun_pellet_jitter: Caller = .player_update_gauss_shotgun_pellet_jitter;
pub const player_update_gauss_shotgun_pellet_speed_scale: Caller = .player_update_gauss_shotgun_pellet_speed_scale;
pub const player_update_plasma_shotgun_pellet_jitter: Caller = .player_update_plasma_shotgun_pellet_jitter;
pub const player_update_plasma_shotgun_pellet_speed_scale: Caller = .player_update_plasma_shotgun_pellet_speed_scale;
pub const player_update_fire_cough_spread_dir: Caller = .player_update_fire_cough_spread_dir;
pub const player_update_fire_cough_spread_mag: Caller = .player_update_fire_cough_spread_mag;
pub const player_update_fire_cough_interval_reset: Caller = .player_update_fire_cough_interval_reset;
pub const player_update_hot_tempered_interval_reset: Caller = .player_update_hot_tempered_interval_reset;
pub const player_update_man_bomb_ion_rifle_angle: Caller = .player_update_man_bomb_ion_rifle_angle;
pub const player_update_man_bomb_ion_minigun_angle: Caller = .player_update_man_bomb_ion_minigun_angle;
pub const creature_alloc_slot_phase_seed: Caller = .creature_alloc_slot_phase_seed;
pub const survival_spawn_creature_type_roll: Caller = .survival_spawn_creature_type_roll;
pub const survival_spawn_creature_parity_pick: Caller = .survival_spawn_creature_parity_pick;
pub const survival_spawn_creature_rare_override: Caller = .survival_spawn_creature_rare_override;
pub const survival_spawn_creature_size: Caller = .survival_spawn_creature_size;
pub const survival_spawn_creature_heading: Caller = .survival_spawn_creature_heading;
pub const survival_spawn_creature_health: Caller = .survival_spawn_creature_health;
pub const survival_spawn_creature_low_tint_g: Caller = .survival_spawn_creature_low_tint_g;
pub const survival_spawn_creature_low_tint_b: Caller = .survival_spawn_creature_low_tint_b;
pub const survival_spawn_creature_mid_tint_g: Caller = .survival_spawn_creature_mid_tint_g;
pub const survival_spawn_creature_mid_tint_b: Caller = .survival_spawn_creature_mid_tint_b;
pub const survival_spawn_creature_high_tint_g: Caller = .survival_spawn_creature_high_tint_g;
pub const survival_spawn_creature_high_tint_b: Caller = .survival_spawn_creature_high_tint_b;
pub const survival_spawn_creature_reward_bonus: Caller = .survival_spawn_creature_reward_bonus;
pub const survival_spawn_creature_rare_red: Caller = .survival_spawn_creature_rare_red;
pub const survival_spawn_creature_rare_green: Caller = .survival_spawn_creature_rare_green;
pub const survival_spawn_creature_rare_blue: Caller = .survival_spawn_creature_rare_blue;
pub const survival_spawn_creature_rare_purple: Caller = .survival_spawn_creature_rare_purple;
pub const survival_spawn_creature_rare_yellow: Caller = .survival_spawn_creature_rare_yellow;
pub const survival_update_extra_spawn_edge: Caller = .survival_update_extra_spawn_edge;
pub const survival_update_extra_spawn_top_x: Caller = .survival_update_extra_spawn_top_x;
pub const survival_update_extra_spawn_bottom_x: Caller = .survival_update_extra_spawn_bottom_x;
pub const survival_update_extra_spawn_left_y: Caller = .survival_update_extra_spawn_left_y;
pub const survival_update_extra_spawn_right_y: Caller = .survival_update_extra_spawn_right_y;
pub const survival_update_main_spawn_edge: Caller = .survival_update_main_spawn_edge;
pub const survival_update_main_spawn_top_x: Caller = .survival_update_main_spawn_top_x;
pub const survival_update_main_spawn_bottom_x: Caller = .survival_update_main_spawn_bottom_x;
pub const survival_update_main_spawn_left_y: Caller = .survival_update_main_spawn_left_y;
pub const survival_update_main_spawn_right_y: Caller = .survival_update_main_spawn_right_y;
pub const creature_spawn_heading: Caller = .creature_spawn_heading;
pub const creature_spawn_reward: Caller = .creature_spawn_reward;
pub const creature_handle_death_split_child_1_phase_seed: Caller = .creature_handle_death_split_child_1_phase_seed;
pub const creature_handle_death_split_child_2_phase_seed: Caller = .creature_handle_death_split_child_2_phase_seed;
pub const creature_handle_death_freeze_shard_angle: Caller = .creature_handle_death_freeze_shard_angle;
pub const creature_handle_death_freeze_shatter_angle: Caller = .creature_handle_death_freeze_shatter_angle;
pub const creature_spawn_template_random_heading: Caller = .creature_spawn_template_random_heading;
pub const creature_spawn_template_base_heading: Caller = .creature_spawn_template_base_heading;
pub const creature_spawn_template_ai1_blue_tint_1a: Caller = .creature_spawn_template_ai1_blue_tint_1a;
pub const creature_spawn_template_ai1_blue_tint_1b: Caller = .creature_spawn_template_ai1_blue_tint_1b;
pub const creature_spawn_template_ai1_blue_tint_1c: Caller = .creature_spawn_template_ai1_blue_tint_1c;
pub const creature_spawn_template_alien_random_1d_size: Caller = .creature_spawn_template_alien_random_1d_size;
pub const creature_spawn_template_alien_random_1d_move_speed: Caller = .creature_spawn_template_alien_random_1d_move_speed;
pub const creature_spawn_template_alien_random_1d_reward: Caller = .creature_spawn_template_alien_random_1d_reward;
pub const creature_spawn_template_alien_random_1d_tint_r: Caller = .creature_spawn_template_alien_random_1d_tint_r;
pub const creature_spawn_template_alien_random_1d_tint_g: Caller = .creature_spawn_template_alien_random_1d_tint_g;
pub const creature_spawn_template_alien_random_1d_tint_b: Caller = .creature_spawn_template_alien_random_1d_tint_b;
pub const creature_spawn_template_alien_random_1d_contact_damage: Caller = .creature_spawn_template_alien_random_1d_contact_damage;
pub const creature_spawn_template_alien_random_1e_size: Caller = .creature_spawn_template_alien_random_1e_size;
pub const creature_spawn_template_alien_random_1e_move_speed: Caller = .creature_spawn_template_alien_random_1e_move_speed;
pub const creature_spawn_template_alien_random_1e_reward: Caller = .creature_spawn_template_alien_random_1e_reward;
pub const creature_spawn_template_alien_random_1e_tint_r: Caller = .creature_spawn_template_alien_random_1e_tint_r;
pub const creature_spawn_template_alien_random_1e_tint_g: Caller = .creature_spawn_template_alien_random_1e_tint_g;
pub const creature_spawn_template_alien_random_1e_tint_b: Caller = .creature_spawn_template_alien_random_1e_tint_b;
pub const creature_spawn_template_alien_random_1e_contact_damage: Caller = .creature_spawn_template_alien_random_1e_contact_damage;
pub const creature_spawn_template_alien_random_1f_size: Caller = .creature_spawn_template_alien_random_1f_size;
pub const creature_spawn_template_alien_random_1f_move_speed: Caller = .creature_spawn_template_alien_random_1f_move_speed;
pub const creature_spawn_template_alien_random_1f_reward: Caller = .creature_spawn_template_alien_random_1f_reward;
pub const creature_spawn_template_alien_random_1f_tint_r: Caller = .creature_spawn_template_alien_random_1f_tint_r;
pub const creature_spawn_template_alien_random_1f_tint_g: Caller = .creature_spawn_template_alien_random_1f_tint_g;
pub const creature_spawn_template_alien_random_1f_tint_b: Caller = .creature_spawn_template_alien_random_1f_tint_b;
pub const creature_spawn_template_alien_random_1f_contact_damage: Caller = .creature_spawn_template_alien_random_1f_contact_damage;
pub const creature_spawn_template_alien_random_green_20_size: Caller = .creature_spawn_template_alien_random_green_20_size;
pub const creature_spawn_template_alien_random_green_20_move_speed: Caller = .creature_spawn_template_alien_random_green_20_move_speed;
pub const creature_spawn_template_alien_random_green_20_tint_g: Caller = .creature_spawn_template_alien_random_green_20_tint_g;
pub const creature_spawn_template_alien_random_green_20_contact_damage: Caller = .creature_spawn_template_alien_random_green_20_contact_damage;
pub const creature_spawn_template_spider_sp1_random_03_size: Caller = .creature_spawn_template_spider_sp1_random_03_size;
pub const creature_spawn_template_spider_sp1_random_03_move_speed: Caller = .creature_spawn_template_spider_sp1_random_03_move_speed;
pub const creature_spawn_template_spider_sp1_random_03_tint_b: Caller = .creature_spawn_template_spider_sp1_random_03_tint_b;
pub const creature_spawn_template_spider_sp1_random_03_contact_damage: Caller = .creature_spawn_template_spider_sp1_random_03_contact_damage;
pub const creature_spawn_template_spider_sp2_random_05_size: Caller = .creature_spawn_template_spider_sp2_random_05_size;
pub const creature_spawn_template_spider_sp2_random_05_move_speed: Caller = .creature_spawn_template_spider_sp2_random_05_move_speed;
pub const creature_spawn_template_spider_sp2_random_05_tint_b: Caller = .creature_spawn_template_spider_sp2_random_05_tint_b;
pub const creature_spawn_template_spider_sp2_random_05_contact_damage: Caller = .creature_spawn_template_spider_sp2_random_05_contact_damage;
pub const creature_spawn_template_lizard_random_04_size: Caller = .creature_spawn_template_lizard_random_04_size;
pub const creature_spawn_template_lizard_random_04_move_speed: Caller = .creature_spawn_template_lizard_random_04_move_speed;
pub const creature_spawn_template_lizard_random_04_contact_damage: Caller = .creature_spawn_template_lizard_random_04_contact_damage;
pub const creature_spawn_template_alien_random_06_size: Caller = .creature_spawn_template_alien_random_06_size;
pub const creature_spawn_template_alien_random_06_move_speed: Caller = .creature_spawn_template_alien_random_06_move_speed;
pub const creature_spawn_template_alien_random_06_tint_b: Caller = .creature_spawn_template_alien_random_06_tint_b;
pub const creature_spawn_template_alien_random_06_contact_damage: Caller = .creature_spawn_template_alien_random_06_contact_damage;
pub const creature_spawn_template_lizard_random_31_size: Caller = .creature_spawn_template_lizard_random_31_size;
pub const creature_spawn_template_lizard_random_31_move_speed: Caller = .creature_spawn_template_lizard_random_31_move_speed;
pub const creature_spawn_template_lizard_random_31_tint: Caller = .creature_spawn_template_lizard_random_31_tint;
pub const creature_spawn_template_spider_sp1_random_32_size: Caller = .creature_spawn_template_spider_sp1_random_32_size;
pub const creature_spawn_template_spider_sp1_random_32_move_speed: Caller = .creature_spawn_template_spider_sp1_random_32_move_speed;
pub const creature_spawn_template_spider_sp1_random_32_tint: Caller = .creature_spawn_template_spider_sp1_random_32_tint;
pub const creature_spawn_template_spider_sp1_random_red_33_size: Caller = .creature_spawn_template_spider_sp1_random_red_33_size;
pub const creature_spawn_template_spider_sp1_random_red_33_move_speed: Caller = .creature_spawn_template_spider_sp1_random_red_33_move_speed;
pub const creature_spawn_template_spider_sp1_random_red_33_tint_r: Caller = .creature_spawn_template_spider_sp1_random_red_33_tint_r;
pub const creature_spawn_template_spider_sp1_random_red_33_contact_damage: Caller = .creature_spawn_template_spider_sp1_random_red_33_contact_damage;
pub const creature_spawn_template_spider_sp1_random_green_34_size: Caller = .creature_spawn_template_spider_sp1_random_green_34_size;
pub const creature_spawn_template_spider_sp1_random_green_34_move_speed: Caller = .creature_spawn_template_spider_sp1_random_green_34_move_speed;
pub const creature_spawn_template_spider_sp1_random_green_34_tint_g: Caller = .creature_spawn_template_spider_sp1_random_green_34_tint_g;
pub const creature_spawn_template_spider_sp1_random_green_34_contact_damage: Caller = .creature_spawn_template_spider_sp1_random_green_34_contact_damage;
pub const creature_spawn_template_lizard_random_2e_size: Caller = .creature_spawn_template_lizard_random_2e_size;
pub const creature_spawn_template_lizard_random_2e_move_speed: Caller = .creature_spawn_template_lizard_random_2e_move_speed;
pub const creature_spawn_template_lizard_random_2e_tint_r: Caller = .creature_spawn_template_lizard_random_2e_tint_r;
pub const creature_spawn_template_lizard_random_2e_tint_g: Caller = .creature_spawn_template_lizard_random_2e_tint_g;
pub const creature_spawn_template_lizard_random_2e_tint_b: Caller = .creature_spawn_template_lizard_random_2e_tint_b;
pub const creature_spawn_template_lizard_random_2e_contact_damage: Caller = .creature_spawn_template_lizard_random_2e_contact_damage;
pub const creature_spawn_template_spider_sp2_random_35_size: Caller = .creature_spawn_template_spider_sp2_random_35_size;
pub const creature_spawn_template_spider_sp2_random_35_move_speed: Caller = .creature_spawn_template_spider_sp2_random_35_move_speed;
pub const creature_spawn_template_spider_sp2_random_35_tint_g: Caller = .creature_spawn_template_spider_sp2_random_35_tint_g;
pub const creature_spawn_template_spider_sp2_random_35_contact_damage: Caller = .creature_spawn_template_spider_sp2_random_35_contact_damage;
pub const creature_spawn_template_ai7_orbiter_tint_g: Caller = .creature_spawn_template_ai7_orbiter_tint_g;
pub const creature_spawn_template_spider_sp1_random_3d_tint: Caller = .creature_spawn_template_spider_sp1_random_3d_tint;
pub const creature_spawn_template_spider_sp1_random_3d_size: Caller = .creature_spawn_template_spider_sp1_random_3d_size;
pub const creature_spawn_template_spider_sp1_ai7_timer_38_size: Caller = .creature_spawn_template_spider_sp1_ai7_timer_38_size;
pub const creature_spawn_template_spider_sp2_ranged_variant_37_size: Caller = .creature_spawn_template_spider_sp2_ranged_variant_37_size;
pub const creature_spawn_template_spider_sp1_ai7_timer_weak_39_size: Caller = .creature_spawn_template_spider_sp1_ai7_timer_weak_39_size;
pub const creature_spawn_template_zombie_random_41_size: Caller = .creature_spawn_template_zombie_random_41_size;
pub const creature_spawn_template_zombie_random_41_tint: Caller = .creature_spawn_template_zombie_random_41_tint;
pub const creature_spawn_template_zombie_random_41_contact_damage: Caller = .creature_spawn_template_zombie_random_41_contact_damage;
pub const creature_update_all_ai7_link_timer_hold: Caller = .creature_update_all_ai7_link_timer_hold;
pub const creature_update_all_ai7_link_timer_reset: Caller = .creature_update_all_ai7_link_timer_reset;
pub const creature_update_all_contact_sfx: Caller = .creature_update_all_contact_sfx;
pub const creature_update_all_plasmaminigun_cooldown: Caller = .creature_update_all_plasmaminigun_cooldown;
pub const creature_update_all_plague_kill_sfx: Caller = .creature_update_all_plague_kill_sfx;
pub const creature_update_all_ping_pong_blood_8_angle: Caller = .creature_update_all_ping_pong_blood_8_angle;
pub const creature_update_all_ping_pong_blood_6_angle: Caller = .creature_update_all_ping_pong_blood_6_angle;
pub const creature_update_all_ping_pong_blood_5_angle: Caller = .creature_update_all_ping_pong_blood_5_angle;
pub const creature_apply_damage_heading_jitter: Caller = .creature_apply_damage_heading_jitter;
pub const creature_apply_damage_pyromaniac: Caller = .creature_apply_damage_pyromaniac;
pub const creature_apply_damage_death_sfx: Caller = .creature_apply_damage_death_sfx;
pub const creature_apply_damage_shock_burst_rotation: Caller = .creature_apply_damage_shock_burst_rotation;
pub const creature_apply_damage_shock_burst_vel_x: Caller = .creature_apply_damage_shock_burst_vel_x;
pub const creature_apply_damage_shock_burst_vel_y: Caller = .creature_apply_damage_shock_burst_vel_y;
pub const creature_apply_damage_shock_burst_scale_step: Caller = .creature_apply_damage_shock_burst_scale_step;
pub const bonus_apply_freeze_shard_angle: Caller = .bonus_apply_freeze_shard_angle;
pub const bonus_apply_freeze_shatter_angle: Caller = .bonus_apply_freeze_shatter_angle;
pub const projectile_update_poison_bullets_gate: Caller = .projectile_update_poison_bullets_gate;
pub const projectile_update_blade_gun_splatter_angle: Caller = .projectile_update_blade_gun_splatter_angle;
pub const projectile_update_bloody_mess_spread: Caller = .projectile_update_bloody_mess_spread;
pub const projectile_update_default_reverse_splatter_gate: Caller = .projectile_update_default_reverse_splatter_gate;
pub const projectile_update_bloody_mess_decal_dx_1: Caller = .projectile_update_bloody_mess_decal_dx_1;
pub const projectile_update_bloody_mess_decal_dy_1: Caller = .projectile_update_bloody_mess_decal_dy_1;
pub const projectile_update_bloody_mess_decal_dx_2: Caller = .projectile_update_bloody_mess_decal_dx_2;
pub const projectile_update_bloody_mess_decal_dy_2: Caller = .projectile_update_bloody_mess_decal_dy_2;
pub const projectile_update_stop_on_hit_jitter: Caller = .projectile_update_stop_on_hit_jitter;
pub const projectile_update_post_hit_decal_burn: Caller = .projectile_update_post_hit_decal_burn;
pub const projectile_update_default_freeze_shard_angle: Caller = .projectile_update_default_freeze_shard_angle;
pub const projectile_update_decal_spread: Caller = .projectile_update_decal_spread;
pub const projectile_update_large_streak_dist: Caller = .projectile_update_large_streak_dist;
pub const projectile_update_large_streak_dist_gt4: Caller = .projectile_update_large_streak_dist_gt4;
pub const projectile_update_large_streak_dist_gt7: Caller = .projectile_update_large_streak_dist_gt7;
pub const projectile_update_large_streak_burn: Caller = .projectile_update_large_streak_burn;
pub const projectile_update_large_streak_freeze_angle: Caller = .projectile_update_large_streak_freeze_angle;
pub const projectile_update_hit_sfx: Caller = .projectile_update_hit_sfx;
pub const projectile_update_particle_jitter_flamethrower: Caller = .projectile_update_particle_jitter_flamethrower;
pub const projectile_update_particle_jitter_bubblegun: Caller = .projectile_update_particle_jitter_bubblegun;
pub const projectile_update_particle_jitter_alt: Caller = .projectile_update_particle_jitter_alt;
pub const projectile_update_particle_bounce_speed_scale: Caller = .projectile_update_particle_bounce_speed_scale;
pub const projectile_update_particle_sprite_vel_x: Caller = .projectile_update_particle_sprite_vel_x;
pub const projectile_update_particle_sprite_vel_y: Caller = .projectile_update_particle_sprite_vel_y;
pub const secondary_projectile_update_pre_hit_decal_dx_1: Caller = .secondary_projectile_update_pre_hit_decal_dx_1;
pub const secondary_projectile_update_pre_hit_decal_dy_1: Caller = .secondary_projectile_update_pre_hit_decal_dy_1;
pub const secondary_projectile_update_pre_hit_decal_dx_2: Caller = .secondary_projectile_update_pre_hit_decal_dx_2;
pub const secondary_projectile_update_pre_hit_decal_dy_2: Caller = .secondary_projectile_update_pre_hit_decal_dy_2;
pub const secondary_projectile_update_pre_hit_decal_dx_3: Caller = .secondary_projectile_update_pre_hit_decal_dx_3;
pub const secondary_projectile_update_pre_hit_decal_dy_3: Caller = .secondary_projectile_update_pre_hit_decal_dy_3;
pub const secondary_projectile_update_pre_hit_freeze_shard_angle: Caller = .secondary_projectile_update_pre_hit_freeze_shard_angle;
pub const secondary_projectile_update_rocket_freeze_shard_angle: Caller = .secondary_projectile_update_rocket_freeze_shard_angle;
pub const secondary_projectile_update_rocket_decal_angle: Caller = .secondary_projectile_update_rocket_decal_angle;
pub const secondary_projectile_update_rocket_decal_radius: Caller = .secondary_projectile_update_rocket_decal_radius;
pub const secondary_projectile_update_seeker_rocket_freeze_shard_angle: Caller = .secondary_projectile_update_seeker_rocket_freeze_shard_angle;
pub const secondary_projectile_update_seeker_rocket_decal_angle: Caller = .secondary_projectile_update_seeker_rocket_decal_angle;
pub const secondary_projectile_update_seeker_rocket_decal_radius: Caller = .secondary_projectile_update_seeker_rocket_decal_radius;
pub const secondary_projectile_update_rocket_minigun_freeze_shard_angle: Caller = .secondary_projectile_update_rocket_minigun_freeze_shard_angle;
pub const secondary_projectile_update_rocket_minigun_decal_angle: Caller = .secondary_projectile_update_rocket_minigun_decal_angle;
pub const secondary_projectile_update_rocket_minigun_decal_radius: Caller = .secondary_projectile_update_rocket_minigun_decal_radius;
pub const secondary_projectile_update_detonation_sprite_mag: Caller = .secondary_projectile_update_detonation_sprite_mag;
pub const unlock_terrain_q4: Caller = .unlock_terrain_q4;
pub const unlock_terrain_q3: Caller = .unlock_terrain_q3;
pub const unlock_terrain_q2: Caller = .unlock_terrain_q2;
pub const terrain_generate_random_prelude_1: Caller = .terrain_generate_random_prelude_1;
pub const terrain_generate_random_prelude_2: Caller = .terrain_generate_random_prelude_2;
pub const terrain_generate_random_prelude_3: Caller = .terrain_generate_random_prelude_3;
pub const terrain_generate_random_base_rotation: Caller = .terrain_generate_random_base_rotation;
pub const terrain_generate_random_base_y: Caller = .terrain_generate_random_base_y;
pub const terrain_generate_random_base_x: Caller = .terrain_generate_random_base_x;
pub const terrain_generate_random_overlay_rotation: Caller = .terrain_generate_random_overlay_rotation;
pub const terrain_generate_random_overlay_y: Caller = .terrain_generate_random_overlay_y;
pub const terrain_generate_random_overlay_x: Caller = .terrain_generate_random_overlay_x;
pub const terrain_generate_random_detail_rotation: Caller = .terrain_generate_random_detail_rotation;
pub const terrain_generate_random_detail_y: Caller = .terrain_generate_random_detail_y;
pub const terrain_generate_random_detail_x: Caller = .terrain_generate_random_detail_x;
pub const terrain_generate_base_rotation: Caller = .terrain_generate_base_rotation;
pub const terrain_generate_base_y: Caller = .terrain_generate_base_y;
pub const terrain_generate_base_x: Caller = .terrain_generate_base_x;
pub const terrain_generate_overlay_rotation: Caller = .terrain_generate_overlay_rotation;
pub const terrain_generate_overlay_y: Caller = .terrain_generate_overlay_y;
pub const terrain_generate_overlay_x: Caller = .terrain_generate_overlay_x;
pub const terrain_generate_detail_rotation: Caller = .terrain_generate_detail_rotation;
pub const terrain_generate_detail_y: Caller = .terrain_generate_detail_y;
pub const terrain_generate_detail_x: Caller = .terrain_generate_detail_x;
pub const player_take_damage_ninja: Caller = .player_take_damage_ninja;
pub const player_take_damage_dodger: Caller = .player_take_damage_dodger;
pub const player_take_damage_highlander: Caller = .player_take_damage_highlander;
pub const player_take_damage_death_sfx: Caller = .player_take_damage_death_sfx;
pub const player_take_damage_pain_sfx: Caller = .player_take_damage_pain_sfx;
pub const player_take_damage_heading: Caller = .player_take_damage_heading;
pub const player_take_damage_low_health: Caller = .player_take_damage_low_health;
pub const fx_queue_add_random_gray: Caller = .fx_queue_add_random_gray;
pub const fx_queue_add_random_width: Caller = .fx_queue_add_random_width;
pub const fx_queue_add_random_rotation: Caller = .fx_queue_add_random_rotation;
pub const fx_queue_add_random_effect_id: Caller = .fx_queue_add_random_effect_id;
pub const fx_spawn_particle_alloc: Caller = .fx_spawn_particle_alloc;
pub const fx_spawn_particle_spin: Caller = .fx_spawn_particle_spin;
pub const fx_spawn_particle_slow_alloc: Caller = .fx_spawn_particle_slow_alloc;
pub const fx_spawn_particle_slow_spin: Caller = .fx_spawn_particle_slow_spin;
pub const fx_spawn_sprite_alloc: Caller = .fx_spawn_sprite_alloc;
pub const fx_spawn_sprite_rotation: Caller = .fx_spawn_sprite_rotation;
pub const effect_spawn_blood_splatter_rotation: Caller = .effect_spawn_blood_splatter_rotation;
pub const effect_spawn_blood_splatter_half: Caller = .effect_spawn_blood_splatter_half;
pub const effect_spawn_blood_splatter_speed_x: Caller = .effect_spawn_blood_splatter_speed_x;
pub const effect_spawn_blood_splatter_speed_y: Caller = .effect_spawn_blood_splatter_speed_y;
pub const effect_spawn_blood_splatter_scale_step: Caller = .effect_spawn_blood_splatter_scale_step;
pub const effect_spawn_burst_rotation: Caller = .effect_spawn_burst_rotation;
pub const effect_spawn_burst_vel_x: Caller = .effect_spawn_burst_vel_x;
pub const effect_spawn_burst_vel_y: Caller = .effect_spawn_burst_vel_y;
pub const effect_spawn_burst_scale_step: Caller = .effect_spawn_burst_scale_step;
pub const effect_spawn_freeze_shard_lifetime: Caller = .effect_spawn_freeze_shard_lifetime;
pub const effect_spawn_freeze_shard_rotation: Caller = .effect_spawn_freeze_shard_rotation;
pub const effect_spawn_freeze_shard_half: Caller = .effect_spawn_freeze_shard_half;
pub const effect_spawn_freeze_shard_rotation_step: Caller = .effect_spawn_freeze_shard_rotation_step;
pub const effect_spawn_freeze_shard_scale_step: Caller = .effect_spawn_freeze_shard_scale_step;
pub const effect_spawn_freeze_shard_effect_id: Caller = .effect_spawn_freeze_shard_effect_id;
pub const effect_spawn_freeze_shatter_half: Caller = .effect_spawn_freeze_shatter_half;
pub const effect_spawn_freeze_shatter_rotation_step: Caller = .effect_spawn_freeze_shatter_rotation_step;
pub const effect_spawn_freeze_shatter_shard_angle: Caller = .effect_spawn_freeze_shatter_shard_angle;
pub const effect_spawn_explosion_burst_puff_rotation: Caller = .effect_spawn_explosion_burst_puff_rotation;
pub const effect_spawn_explosion_burst_rotation: Caller = .effect_spawn_explosion_burst_rotation;
pub const effect_spawn_explosion_burst_vel_x: Caller = .effect_spawn_explosion_burst_vel_x;
pub const effect_spawn_explosion_burst_vel_y: Caller = .effect_spawn_explosion_burst_vel_y;
pub const effect_spawn_explosion_burst_scale_step: Caller = .effect_spawn_explosion_burst_scale_step;
pub const effect_spawn_explosion_burst_rotation_step: Caller = .effect_spawn_explosion_burst_rotation_step;
pub const perk_select_random: Caller = .perk_select_random;
pub const perks_generate_choices_rarity_gate: Caller = .perks_generate_choices_rarity_gate;
pub const perk_apply_fatal_lottery: Caller = .perk_apply_fatal_lottery;
pub const perk_apply_bandage_heal: Caller = .perk_apply_bandage_heal;
pub const perks_update_effects_regeneration_gate: Caller = .perks_update_effects_regeneration_gate;
pub const perks_update_effects_pyrokinetic_angle_0p8: Caller = .perks_update_effects_pyrokinetic_angle_0p8;
pub const perks_update_effects_pyrokinetic_angle_0p6: Caller = .perks_update_effects_pyrokinetic_angle_0p6;
pub const perks_update_effects_pyrokinetic_angle_0p4: Caller = .perks_update_effects_pyrokinetic_angle_0p4;
pub const perks_update_effects_pyrokinetic_angle_0p3: Caller = .perks_update_effects_pyrokinetic_angle_0p3;
pub const perks_update_effects_pyrokinetic_angle_0p2: Caller = .perks_update_effects_pyrokinetic_angle_0p2;
pub const perks_update_effects_jinxed_accident_gate: Caller = .perks_update_effects_jinxed_accident_gate;
pub const perks_update_effects_jinxed_timer_reset: Caller = .perks_update_effects_jinxed_timer_reset;
pub const perks_update_effects_jinxed_creature_pick: Caller = .perks_update_effects_jinxed_creature_pick;
pub const perks_update_effects_jinxed_creature_retry: Caller = .perks_update_effects_jinxed_creature_retry;
pub const quest_start_selected_highscore_random_tag: Caller = .quest_start_selected_highscore_random_tag;
pub const quest_build_target_practice_angle: Caller = .quest_build_target_practice_angle;
pub const quest_build_target_practice_radius: Caller = .quest_build_target_practice_radius;
pub const quest_build_the_random_factor_brute_gate: Caller = .quest_build_the_random_factor_brute_gate;
pub const quest_build_sweep_stakes_angle: Caller = .quest_build_sweep_stakes_angle;
pub const quest_build_deja_vu_angle: Caller = .quest_build_deja_vu_angle;
pub const quest_build_the_killing_template_pick: Caller = .quest_build_the_killing_template_pick;
pub const quest_build_the_killing_layout_pick: Caller = .quest_build_the_killing_layout_pick;
pub const quest_build_the_killing_spawner_1_y: Caller = .quest_build_the_killing_spawner_1_y;
pub const quest_build_the_killing_spawner_1_x: Caller = .quest_build_the_killing_spawner_1_x;
pub const quest_build_the_killing_spawner_2_y: Caller = .quest_build_the_killing_spawner_2_y;
pub const quest_build_the_killing_spawner_2_x: Caller = .quest_build_the_killing_spawner_2_x;
pub const quest_build_the_killing_spawner_3_y: Caller = .quest_build_the_killing_spawner_3_y;
pub const quest_build_the_killing_spawner_3_x: Caller = .quest_build_the_killing_spawner_3_x;
pub const typo_word_pick_fragment: Caller = .typo_word_pick_fragment;
pub const typo_word_pick_highscore_name: Caller = .typo_word_pick_highscore_name;
pub const typo_target_name_assign_random_highscore_gate: Caller = .typo_target_name_assign_random_highscore_gate;
pub const typo_target_name_assign_random_four_word_gate: Caller = .typo_target_name_assign_random_four_word_gate;
pub const typo_target_name_assign_random_three_word_gate_gt80: Caller = .typo_target_name_assign_random_three_word_gate_gt80;
pub const typo_target_name_assign_random_three_word_gate_gt60: Caller = .typo_target_name_assign_random_three_word_gate_gt60;
pub const typo_target_name_assign_random_two_word_gate_gt40: Caller = .typo_target_name_assign_random_two_word_gate_gt40;
pub const typo_target_name_assign_random_two_word_gate_gt20: Caller = .typo_target_name_assign_random_two_word_gate_gt20;
pub const typo_gameplay_typeclick_backspace: Caller = .typo_gameplay_typeclick_backspace;
pub const typo_gameplay_typeclick_char: Caller = .typo_gameplay_typeclick_char;
pub const creature_spawn_tinted_heading: Caller = .creature_spawn_tinted_heading;
pub const creature_spawn_tinted_size: Caller = .creature_spawn_tinted_size;
pub const ui_text_input_update_typeclick: Caller = .ui_text_input_update_typeclick;
pub const credits_secret_alien_zookeeper_fill_empty: Caller = .credits_secret_alien_zookeeper_fill_empty;
pub const credits_secret_alien_zookeeper_reroll_fill: Caller = .credits_secret_alien_zookeeper_reroll_fill;
pub const sfx_play_exclusive_playlist_pick: Caller = .sfx_play_exclusive_playlist_pick;
pub const camera_update_offset_x_base: Caller = .camera_update_offset_x_base;
pub const camera_update_offset_x_spread: Caller = .camera_update_offset_x_spread;
pub const camera_update_offset_x_sign: Caller = .camera_update_offset_x_sign;
pub const camera_update_offset_y_base: Caller = .camera_update_offset_y_base;
pub const camera_update_offset_y_spread: Caller = .camera_update_offset_y_spread;
pub const camera_update_offset_y_sign: Caller = .camera_update_offset_y_sign;
pub const demo_setup_variant_1_spider_sp1_x: Caller = .demo_setup_variant_1_spider_sp1_x;
pub const demo_setup_variant_1_spider_sp1_y: Caller = .demo_setup_variant_1_spider_sp1_y;
pub const demo_setup_variant_1_spider_sp2_x: Caller = .demo_setup_variant_1_spider_sp2_x;
pub const demo_setup_variant_1_spider_sp2_y: Caller = .demo_setup_variant_1_spider_sp2_y;
pub const demo_setup_variant_3_alien_big_x: Caller = .demo_setup_variant_3_alien_big_x;
pub const demo_setup_variant_3_alien_big_y: Caller = .demo_setup_variant_3_alien_big_y;
pub const demo_setup_variant_3_alien_small_x: Caller = .demo_setup_variant_3_alien_small_x;
pub const demo_setup_variant_3_alien_small_y: Caller = .demo_setup_variant_3_alien_small_y;
pub const shrinkifier_hit_rotation: Caller = .shrinkifier_hit_rotation;
pub const shrinkifier_hit_vel_x: Caller = .shrinkifier_hit_vel_x;
pub const shrinkifier_hit_vel_y: Caller = .shrinkifier_hit_vel_y;
pub const shrinkifier_hit_scale_step: Caller = .shrinkifier_hit_scale_step;
pub const splitter_hit_angle: Caller = .splitter_hit_angle;
pub const splitter_hit_radius: Caller = .splitter_hit_radius;
pub const splitter_hit_age: Caller = .splitter_hit_age;
pub const ion_hit_spark_rotation: Caller = .ion_hit_spark_rotation;
pub const ion_hit_spark_vel_x: Caller = .ion_hit_spark_vel_x;
pub const ion_hit_spark_vel_y: Caller = .ion_hit_spark_vel_y;
pub const ion_hit_spark_scale_step: Caller = .ion_hit_spark_scale_step;
pub const weapon_pick_random_available_pick: Caller = .weapon_pick_random_available_pick;
pub const weapon_pick_random_available_reroll_gate: Caller = .weapon_pick_random_available_reroll_gate;
pub const weapon_pick_random_available_reroll_pick: Caller = .weapon_pick_random_available_reroll_pick;
pub const rewrite_jinxed_accident_target_pick: Caller = .rewrite_jinxed_accident_target_pick;
pub const game_frame_update_discarded: Caller = .game_frame_update_discarded;
pub const rewrite_stats_menu_easter_roll: Caller = .rewrite_stats_menu_easter_roll;
pub const rewrite_stats_menu_easter_text_x: Caller = .rewrite_stats_menu_easter_text_x;
