const game_ids = @import("crimson_zig").game_ids;

pub const CreditLine = struct {
    text: []const u8,
    heading: bool = false,
};

pub fn perkDescription(perk_id: game_ids.PerkId) []const u8 {
    return switch (perk_id) {
        .antiperk => "You shouldn't be seeing this..",
        .bloody_mess_quick_learner => "More the merrier. More blood guarantees a 30% better experience. You spill more blood and gain more experience points.",
        .sharpshooter => "Miraculously your aiming improves drastically, but you take a little bit more time on actually firing the gun. If you order now, you also get a fancy LASER SIGHT without ANY charge!",
        .fastloader => "Man, you sure know how to load a gun.",
        .lean_mean_exp_machine => "Why kill for experience when you can make some of your own for free! With this perk the experience just keeps flowing in at a constant rate.",
        .long_distance_runner => "You move like a train that has feet and runs. You just need a little time to warm up. In other words you'll move faster the longer you run without stopping.",
        .pyrokinetic => "You see flames everywhere. Bare aiming at creatures causes them to heat up.",
        .instant_winner => "2500 experience points. Right away. Take it or leave it.",
        .grim_deal => "I'll make you a deal: I'll give you 18% more experience points, and you'll give me your life. So you'll die but score higher. Ponder that one for a sec.",
        .alternate_weapon => "Ever fancied about having two weapons available for use? This might be your lucky day; with this perk you'll get an extra weapon slot for another gun! Carrying around two guns slows you down slightly though. (You can switch the weapon slots with RELOAD key)",
        .plaguebearer => "You carry a horrible disease. Good for you: you are immune. Bad for them: it is contagious! (Monsters become resistant over time though.)",
        .evil_eyes => "No living (nor dead) can resist the hypnotic power of your eyes: monsters freeze still as you look at them!",
        .ammo_maniac => "You squeeze and you push and you pack your clips with about 20% more ammo than a regular fellow. They call you Ammo Maniac with a deep respect in their voices.",
        .radioactive => "You are the Radioactive-man; you have that healthy green glow around you! Others don't like it though, it makes them sick and nauseous whenever near you. It does affect your social life a bit.",
        .fastshot => "Funny how you make your gun spit bullets faster than the next guy. Even the most professional of engineers are astonished.",
        .fatal_lottery => "Fifty-fifty chance of dying OR gaining 10k experience points. Place your bets. Interested, anyone?",
        .random_weapon => "Here, have this weapon. No questions asked.",
        .mr_melee => "You master the art of melee fighting. You don't just stand still when monsters come near -- you hit back. Hard.",
        .anxious_loader => "When you can't stand waiting your gun to be reloaded you can speed up the process by clicking your FIRE button repeatedly as fast as you can.",
        .final_revenge => "Pick this and you'll get your revenge. It's a promise.",
        .telekinetic => "Picking up bonuses has never been so easy and FUN. You can pick up bonuses simply by aiming at them for a while. Ingenious.",
        .perk_expert => "You sure know how to pick a perk -- most people just don't see that extra perk laying around. This gives you the opportunity to pick the freshest and shiniest perks from the top.",
        .unstoppable => "Monsters can't slow you down with their nasty scratches and bites. It still hurts but you simply ignore the pain.",
        .regression_bullets => "Attempt to shoot with an empty clip leads to a severe loss of experience. But hey, whatever makes them go down, right?",
        .infernal_contract => "In exchange for your soul, a dark stranger is offering you three (3) new perks. To collect his part of the bargain soon enough, your health is reduced to a near-death status. Just sign down here below this pentagram..",
        .poison_bullets => "You tend to explicitly treat each of your bullets with rat poison. You do it for good luck, but it seems to have other side effects too.",
        .dodger => "It seems so stupid just to take the hits. Each time a monster attacks you you have a chance to dodge the attack.",
        .bonus_magnet => "You somehow seem to lure all kinds of bonuses to appear around you more often.",
        .uranium_filled_bullets => "Your bullets have a nice creamy uranium filling. Yummy. Now that's gotta hurt the monsters more, right?",
        .doctor => "With a single glance you can tell the medical condition of, well, anything. Also, being a doctor, you know exactly what hurts the most enabling you to do slightly more damage with your attacks.",
        .monster_vision => "With your newly enhanced senses you can see all bad energy VERY clearly. That's got to be enough.",
        .hot_tempered => "It literally boils inside you. That's exactly why you need to let it out once in a while, unfortunately for those near you.",
        .bonus_economist => "Your bonus power-ups last 50% longer than they normally would.",
        .thick_skinned => "Trade 1/3 of your health for only receiving 2/3rds damage on attacks.",
        .barrel_greaser => "After studying a lot of physics and friction you've come up with a way to make your bullets fly faster. More speed, more damage.",
        .ammunition_within => "Empty clip doesn't prevent you from shooting with a weapon; instead the ammunition is drawn from your health while you are reloading.",
        .veins_of_poison => "A strong poison runs through your veins. Monsters taking a bite of you are eventually to experience an agonizing death.",
        .toxic_avenger => "You started out just by being poisonous. The next logical step for you is to become highly toxic -- the ULTIMATE TOXIC AVENGER. Most monsters touching you will just drop dead within seconds!",
        .regeneration => "Your health replenishes but very slowly. What more there is to say?",
        .pyromaniac => "You just enjoy using fire as your Tool of Destruction and you're good at it too; your fire based weapons do a lot more damage.",
        .ninja => "You've taken your dodging abilities to the next level; monsters have really hard time hitting you.",
        .highlander => "You are immortal. Well, almost immortal. Instead of actually losing health on attacks you've got a 10% chance of just dropping dead whenever a monster attacks you. There really can be only one, you know.",
        .jinxed => "Things happen near you. Strangest things. Creatures just drop dead and accidents happen. Beware.",
        .perk_master => "Being the Perk Expert taught you a few things and now you are ready to take your training to the next level doubling the ability effect.",
        .reflex_boosted => "To you the world seems to go on about 10% slower than to an average person. It can be rather irritating sometimes, but it does give you a chance to react better.",
        .greater_regeneration => "Your health replenishes faster than ever.",
        .breathing_room => "Trade 2/3rds of your health for the killing of every single creature on the screen. No, you don't get the experience.",
        .death_clock => "You die exactly in 30 seconds. You can't escape your destiny, but feel free to go on a spree. Tick, tock.",
        .my_favourite_weapon => "You've grown very fond of your piece. You polish it all the time and talk nice to it, your precious. (+2 clip size, no more random weapon bonuses)",
        .bandage => "Here, eat this bandage and you'll feel a lot better in no time. (restores up to 50% health)",
        .angry_reloader => "You hate it when you run out of shots. You HATE HATE HATE reloading your gun. Lucky for you, and strangely enough, your hate materializes as Mighty Balls of Fire. Or more like Quite Decent Balls of Fire, but it's still kinda neat, huh?",
        .ion_gun_master => "You're good with ion weapons. You're so good that not only your shots do slightly more damage but your ion blast radius is also increased.",
        .stationary_reloader => "It's incredibly hard to reload your piece while moving around, you've noticed. In fact, realizing that, when you don't move a (leg) muscle you can reload the gun THREE TIMES FASTER!",
        .man_bomb => "You have the ability to go boom for you are the MAN BOMB. Going boom requires a lot of concentration and standing completely still for a few seconds.",
        .fire_caugh => "You have a fireball stuck in your throat. Repeatedly. Mind your manners.",
        .living_fortress => "It comes a time in each man's life when you'd just rather not move anymore. Being living fortress not moving comes with extra benefits as well. You do the more damage the longer you stand still.",
        .tough_reloader => "Damage received during reloading a weapon is halved.",
        .lifeline_50_50 => "The computer removes half of the wrong monsters for you. You don't gain any experience.",
    };
}

pub fn perkPrerequisite(perk_id: game_ids.PerkId) ?game_ids.PerkId {
    return switch (perk_id) {
        .toxic_avenger => .veins_of_poison,
        .ninja => .dodger,
        .perk_master => .perk_expert,
        .greater_regeneration => .regeneration,
        else => null,
    };
}

pub const credits_lines = [_]CreditLine{
    .{ .text = "2026 Remake:", .heading = true },
    .{ .text = "banteg" },
    .{ .text = "Crimsonland", .heading = true },
    .{ .text = "Game Design:", .heading = true },
    .{ .text = "Tero Alatalo" },
    .{ .text = "Programming:", .heading = true },
    .{ .text = "Tero Alatalo" },
    .{ .text = "Producer:", .heading = true },
    .{ .text = "Zach Young" },
    .{ .text = "2D Art:", .heading = true },
    .{ .text = "Tero Alatalo" },
    .{ .text = "3D Modelling:", .heading = true },
    .{ .text = "Tero Alatalo" },
    .{ .text = "Timo Palonen" },
    .{ .text = "Music:", .heading = true },
    .{ .text = "Valtteri Pihlajam" },
    .{ .text = "Ville Eriksson" },
    .{ .text = "Sound Effects:", .heading = true },
    .{ .text = "Ion Hardie" },
    .{ .text = "Tero Alatalo" },
    .{ .text = "Valtteri Pihlajam" },
    .{ .text = "Ville Eriksson" },
    .{ .text = "Manual:", .heading = true },
    .{ .text = "Miikka Kulmala" },
    .{ .text = "Zach Young" },
    .{ .text = "Special thanks to:", .heading = true },
    .{ .text = "Petri J" },
    .{ .text = "Peter Hajba / Remedy" },
    .{ .text = "Play testers:", .heading = true },
    .{ .text = "Avraham Petrosyan" },
    .{ .text = "Bryce Baker" },
    .{ .text = "Dan Ruskin" },
    .{ .text = "Dirk Bunk" },
    .{ .text = "Eric Dallaire" },
    .{ .text = "Erik Van Pelt" },
    .{ .text = "Ernie Ramirez" },
    .{ .text = "Ion Hardie" },
    .{ .text = "James C. Smith" },
    .{ .text = "Jarkko Forsbacka" },
    .{ .text = "Jeff McAteer" },
    .{ .text = "Juha Alatalo" },
    .{ .text = "Kalle Hahl" },
    .{ .text = "Lars Brubaker" },
    .{ .text = "Lee Cooper" },
    .{ .text = "Markus Lassila" },
    .{ .text = "Matti Alanen" },
    .{ .text = "Miikka Kulmala" },
    .{ .text = "Mika Alatalo" },
    .{ .text = "Mike Colonnese" },
    .{ .text = "Simon Hallam" },
    .{ .text = "Toni Nurminen" },
    .{ .text = "Valtteri Pihlajam" },
    .{ .text = "Ville Eriksson" },
    .{ .text = "Ville M" },
    .{ .text = "Zach Young" },
    .{ .text = "2003 (c) 10tons entertainment" },
    .{ .text = "10tons logo by" },
    .{ .text = "Pasi Heinonen" },
    .{ .text = "Uses Vorbis Audio Decompression" },
    .{ .text = "2003 (c) Xiph.Org Foundation" },
    .{ .text = "(see vorbis.txt)" },
    .{ .text = "You can stop watching now." },
    .{ .text = "Click the ones with the round ones!" },
    .{ .text = "(and be patient!)" },
};
