IMAGE=grim.dll
FUNCTION=grim_jpeg_init_memory_mgr
COMPILER=msvc6.5
SYMBOL=jinit_memory_mgr
SOURCE=../../shared/grim_jaz_jpeg_memory.c
NOTE=ijg-6a-jaz-memory-manager-initializer
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DMAX_ALLOC_CHUNK=65520 /DHAVE_STDLIB_H /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='grim_jaz_operator_new:??2@YAPAXI@Z,jpeg_mem_init:grim_jpeg_mem_init,jpeg_mem_term:grim_noop,alloc_small:grim_jpeg_alloc_small,alloc_large:grim_jpeg_alloc_large,alloc_sarray:grim_jpeg_alloc_sarray,alloc_barray:grim_jpeg_alloc_barray,request_virt_sarray:grim_jpeg_request_virt_sarray,request_virt_barray:grim_jpeg_request_virt_barray,realize_virt_arrays:grim_jpeg_realize_virt_arrays,access_virt_sarray:grim_jpeg_access_virt_sarray,access_virt_barray:grim_jpeg_access_virt_barray,free_pool:grim_jpeg_free_pool,self_destruct:grim_jpeg_self_destruct'
