IMAGE=grim.dll
FUNCTION=png_zfree
COMPILER=msvc7.0
SYMBOL=grim_png_zfree
SOURCE=../../shared/grim_png_callbacks.cpp
NOTE=png-zfree-callback
CFLAGS="/O1 /G6 /W3 /GR- /MD"
REFERENCE_ALIASES='png_free:png_free'
