IMAGE=crimsonland.exe
FUNCTION=console_cmd_snd_freq_adjustment
SYMBOL=console_cmd_snd_freq_adjustment
SOURCE=../../../../decomp/1.9/crimsonland/crimsonland/console_cmd_snd_freq_adjustment.cpp
NOTE=console-sound-frequency-toggle
