IMAGE=grim.dll
FUNCTION=grim_pixel_format_destroy_dxt
SYMBOL='??1grim_pixel_format_dxt_t@@UAE@XZ'
SOURCE=scratch.cpp
COMPILER=msvc6.5pp
CFLAGS="/O1 /Oi /G6 /W3 /GR- /GX"
REFERENCE_ALIASES='??_7grim_pixel_format_dxt_t@@6B@:grim_pixel_format_vtable_dxt,??1grim_pixel_format_base_t@@UAE@XZ:grim_vertex_space_converter_destroy,__EH_prolog:seh_prolog,$L370:grim_pixel_format_destroy_dxt_eh_handler'
NOTE=grim-dxt-cache-destruction
