from __future__ import annotations

from enum import Enum, auto

# Kept apart from `grim.assets`, which loads raylib: simulation tables (terrain slots) name textures headlessly.


class TextureId(Enum):
    BACKPLASMA = auto()
    MOCKUP = auto()
    LOGO_ESRB = auto()
    LOADING = auto()
    CL_LOGO = auto()
    SPLASH_10TONS = auto()
    SPLASH_REFLEXIVE = auto()
    DEFAULT_FONT_COURIER = auto()
    SMALL_WHITE = auto()
    TROOPER = auto()
    ZOMBIE = auto()
    SPIDER_SP1 = auto()
    SPIDER_SP2 = auto()
    ALIEN = auto()
    LIZARD = auto()
    ARROW = auto()
    BULLET_I = auto()
    BULLET_TRAIL = auto()
    BODYSET = auto()
    PROJS = auto()
    UI_ICON_AIM = auto()
    UI_BUTTON_SM = auto()
    UI_BUTTON_MD = auto()
    UI_CHECK_ON = auto()
    UI_CHECK_OFF = auto()
    UI_RECT_OFF = auto()
    UI_RECT_ON = auto()
    BONUSES = auto()
    UI_IND_BULLET = auto()
    UI_IND_ROCKET = auto()
    UI_IND_ELECTRIC = auto()
    UI_IND_FIRE = auto()
    PARTICLES = auto()
    UI_IND_LIFE = auto()
    UI_IND_PANEL = auto()
    UI_ARROW = auto()
    UI_CURSOR = auto()
    UI_AIM = auto()
    TER_Q1_BASE = auto()
    TER_Q1_OVERLAY = auto()
    TER_Q2_BASE = auto()
    TER_Q2_OVERLAY = auto()
    TER_Q3_BASE = auto()
    TER_Q3_OVERLAY = auto()
    TER_Q4_BASE = auto()
    TER_Q4_OVERLAY = auto()
    UI_TEXT_LEVEL_COMPLETE = auto()
    UI_TEXT_QUEST = auto()
    UI_NUM1 = auto()
    UI_NUM2 = auto()
    UI_NUM3 = auto()
    UI_NUM4 = auto()
    UI_NUM5 = auto()
    UI_WICONS = auto()
    UI_GAME_TOP = auto()
    UI_LIFE_HEART = auto()
    UI_CLOCK_TABLE = auto()
    UI_CLOCK_POINTER = auto()
    MUZZLE_FLASH = auto()
    UI_DROP_ON = auto()
    UI_DROP_OFF = auto()
    UI_SIGN_CRIMSON = auto()
    UI_MENU_ITEM = auto()
    UI_MENU_PANEL = auto()
    UI_ITEM_TEXTS = auto()
    UI_TEXT_REAPER = auto()
    UI_TEXT_WELL_DONE = auto()
    UI_TEXT_CONTROLS = auto()
    UI_TEXT_PICK_A_PERK = auto()
    UI_TEXT_LEVEL_UP = auto()
