IMAGE=grim.dll
FUNCTION=grim_jpeg_reset_marker_reader
SYMBOL=reset_marker_reader
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmarker.c
NOTE=ijg-6a-stock-reset-marker-reader
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
