IMAGE=grim.dll
FUNCTION=d3dx_jpeg_init_d_main_controller
COMPILER=msvc7.0
SYMBOL=jinit_d_main_controller
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmainct.c
NOTE=ijg-6a-d3dx-main-controller-initializer
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='start_pass_main:d3dx_jpeg_start_pass_main,alloc_funny_pointers:d3dx_jpeg_alloc_funny_pointers'
