IMAGE=grim.dll
FUNCTION=jpeg_read_scanlines
SYMBOL=jpeg_read_scanlines
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdapistd.c
NOTE=ijg-6a-stock-read-scanlines
CFLAGS='/O2 /GB /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
