IMAGE=grim.dll
FUNCTION=0x1002ec9d
COMPILER=msvc7.0
SYMBOL='@grim_jpeg_start_iMCU_row_source@4'
SOURCE=../../shared/grim_jpeg_source_helpers.cpp
NOTE=ijg-coefficient-controller-row-initializer
CFLAGS="/O1 /G6 /W3 /GR- /MD"
