IMAGE=grim.dll
FUNCTION=d3dx_sse2_matrix_multiply_transpose_impl
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='objf\i386\d3dxmathsse2.obj'
REFERENCE_ALIASES='.data:d3dx_sse2_math_constants,.data1:d3dx_sse2_math_vectors'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?sse2_D3DXMatrixMultiplyTranspose$$1@@YGPAUD3DXMATRIX@@PAU1@PBU1@1@Z'
NOTE=directx-8.1-archive-d3dx-sse2-matrix-multiply-transpose-impl
