IMAGE=grim.dll
FUNCTION=d3dx_jpeg_ycck_cmyk_convert
COMPILER=msvc7.0
SYMBOL=ycck_cmyk_convert
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdcolor.c
NOTE=ijg-6a-d3dx-ycck-cmyk-converter
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
