IMAGE=grim.dll
FUNCTION=d3dx_image_save
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\cd3dximage.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?Save@CD3DXImage@@QAEJPBXW4_D3DXIMAGE_FILEFORMAT@@H@Z'
REFERENCE_ALIASES='$L52490:d3dx_image_save_eh_handler,__EH_prolog:seh_prolog,_g_pBMPFormats:d3dx_bmp_formats,_g_pDDSFormats:d3dx_dds_formats'
NOTE=directx-8.1-archive-cd3dximage-save
