IMAGE=grim.dll
FUNCTION=grim_jpeg_destroy
SYMBOL=jpeg_destroy
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jcomapi.c
NOTE=ijg-6a-stock-jpeg-destroy
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
