IMAGE=grim.dll
FUNCTION=0x1003acb0
SYMBOL=reset_error_mgr
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jerror.c
NOTE=ijg-6a-stock-reset-error-manager
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
