IMAGE=grim.dll
FUNCTION=zlib_inflate_blocks_new
SYMBOL=inflate_blocks_new
SOURCE=../../../../third_party/sources/zlib-1.1.3/infblock.c
NOTE=zlib-1.1.3-stock-inflate-blocks-new
CFLAGS='/O2 /Ob2 /GB /W3 /MD'
REFERENCE_ALIASES='inflate_blocks_reset:zlib_inflate_blocks_reset,inflate_codes_free:zlib_inflate_codes_free'
