IMAGE=crimsonland.exe
FUNCTION=quest_build_the_annihilation
SYMBOL=quest_build_the_annihilation
SOURCE=../../../../decomp/1.9/crimsonland/quests/quest_build_the_annihilation.cpp
NOTE=quest-the-annihilation-builder
