IMAGE=grim.dll
FUNCTION=grim_pixel_format_init_dxt
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\cd3dxcodec.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='??0CD3DXCodecDXT@@QAE@PAUD3DX_BLT@@@Z'
REFERENCE_ALIASES='??0CD3DXCodec@@IAE@PAUD3DX_BLT@@IK@Z:grim_pixel_format_init,??_7CD3DXCodecDXT@@6B@:grim_pixel_format_vtable_dxt,?D3DXEncodeDXT4@@YAJPAEPBUD3DXCOLOR@@@Z:grim_dxt4_encode_block,?D3DXDecodeDXT4@@YAJPAUD3DXCOLOR@@PBE@Z:grim_dxt4_decode_block,?D3DXEncodeDXT2@@YAJPAEPBUD3DXCOLOR@@@Z:grim_dxt2_encode_block,?D3DXDecodeDXT2@@YAJPAUD3DXCOLOR@@PBE@Z:grim_dxt2_decode_block'
NOTE=directx-8.1-archive-cd3dxcodec-dxt-ctor
