IMAGE=grim.dll
FUNCTION=d3dx_jpeg_get_dqt
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\jdmarker.obj'
REFERENCE_ALIASES='?jpeg_alloc_quant_table@D3DX@@YAPAUJQUANT_TBL@1@PAUjpeg_common_struct@1@@Z:d3dx_jpeg_alloc_quant_table,?jpeg_natural_order@D3DX@@3QBHB:d3dx_jpeg_natural_order'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?get_dqt@D3DX@@YAEPAUjpeg_decompress_struct@1@@Z'
NOTE=directx-8.1-archive-d3dx-jpeg-get-dqt
