IMAGE=grim.dll
FUNCTION=d3dx_jpeg_prepare_for_output_pass
COMPILER=msvc7.0
SYMBOL=prepare_for_output_pass
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmaster.c
NOTE=ijg-6a-d3dx-output-pass-preparation
CFLAGS='/O1 /Oi /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
