IMAGE=crimsonland.exe
FUNCTION='?_GetRangeOfTrysToCheck@@YAPBU_s_TryBlockMapEntry@@PBU_s_FuncInfo@@HHPAI1@Z'
ARCHIVE=../../../native/providers/build/vc6-sp6/vc98/lib/libcmt.lib
ARCHIVE_MEMBER='build\intel\mt_obj\trnsctrl.obj'
ARCHIVE_SHA256=a541c95e5ffdd6d5573d1976f5e5d0038f2c4fb0bcb02975c68948bf1d6e452a
SYMBOL='?_GetRangeOfTrysToCheck@@YAPBU_s_TryBlockMapEntry@@PBU_s_FuncInfo@@HHPAI1@Z'
REFERENCE_ALIASES='?_inconsistency@@YAXXZ:crt_invalid_parameter_noinfo_noreturn'
NOTE=vc6-sp6-libcmt-getrangeoftrystocheck-yapbu-s-tryblockmapentry-pbu-s-funcinfo-hhpai1-z
