IMAGE=grim.dll
FUNCTION=d3dx_jpeg_mem_init
COMPILER=msvc7.0
SYMBOL=jpeg_mem_init
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jmemnobs.c
NOTE=ijg-6a-d3dx-memory-init
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
