IMAGE=grim.dll
FUNCTION=grim_jaz_jpeg_create_decompress
SYMBOL=jpeg_CreateDecompress
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdapimin.c
NOTE=ijg-6a-stock-create-decompress
CFLAGS='/O2 /GB /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='jinit_marker_reader:grim_jpeg_init_marker_reader'
