IMAGE=grim.dll
FUNCTION=grim_pixel_format_ctor_d16_lockable
SYMBOL='??0grim_pixel_format_d16_lockable_t@@QAE@PAI@Z'
SOURCE=../../shared/grim_pixel_format_constructors.cpp
NOTE=d3dx-d16_lockable-pixel-format-constructor
CFLAGS="/O1 /G6 /W3 /GR- /MD"
REFERENCE_ALIASES='??0grim_pixel_format_base_t@@QAE@PAIHH@Z:grim_pixel_format_init'
