IMAGE=grim.dll
FUNCTION=grim_jpeg_memory_src
SYMBOL=grim_jpeg_memory_src
SOURCE=../../../native/providers/sources/ijg-libjpeg-6a/grim_jpeg_memory_src.c
NOTE=jpeg-memory-source-manager
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
