IMAGE=grim.dll
FUNCTION=grim_jpeg_alloc_barray
COMPILER=msvc6.5
SYMBOL=alloc_barray
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jmemmgr.c
NOTE=ijg-6a-jaz-coefficient-array-allocator
CFLAGS='/O2 /G6 /W3 /MD /DMAX_ALLOC_CHUNK=65520 /DHAVE_BOOLEAN /Dboolean="unsigned char"'
