IMAGE=grim.dll
FUNCTION=grim_jpeg_idct_4x4
SYMBOL=jpeg_idct_4x4
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jidctred.c
NOTE=ijg-6a-msvc-short-multiply-four-by-four-inverse-dct
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char" /DSHORTxLCONST_32'
