IMAGE=crimsonland.exe
FUNCTION=console_cmd_set_gamma_ramp
SYMBOL=console_cmd_set_gamma_ramp
SOURCE=../../../../decomp/1.9/crimsonland/crimsonland/console_cmd_set_gamma_ramp.cpp
NOTE=console-gamma-command
