IMAGE=grim.dll
FUNCTION=d3dx_create_texture_from_file_in_memory_ex
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\d3dx8tex.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?CreateTextureFromFileInMemoryEx@@YAJPAUIDirect3DDevice8@@PBXIIIIIKW4_D3DFORMAT@@W4_D3DPOOL@@KKKPAU_D3DXIMAGE_INFO@@PAUtagPALETTEENTRY@@W4_D3DRESOURCETYPE@@PAPAUIDirect3DBaseTexture8@@@Z'
REFERENCE_ALIASES='$L54358:d3dx_create_texture_from_file_in_memory_ex_eh_handler,__EH_prolog:seh_prolog'
NOTE=directx-8.1-archive-create-texture-from-memory
