IMAGE=grim.dll
FUNCTION=inflateInit2_
COMPILER=msvc7.0
SYMBOL=grim_inflate_init2
SOURCE=../../shared/grim_zlib_inflate_source.c
NOTE=zlib-1.1.3-inflate-stream-initializer
CFLAGS="/O1 /G6 /W3 /GR- /MD"
REFERENCE_ALIASES='grim_zcalloc:zcalloc,grim_zcfree:d3dx_jpeg_free_small,grim_inflate_end:inflateEnd,grim_inflate_blocks_new:inflate_blocks_new,grim_adler32:adler32,grim_inflate_reset:inflateReset'
