IMAGE=crimsonland.exe
FUNCTION=console_cmd_set_resource_paq
SYMBOL=console_cmd_set_resource_paq
SOURCE=../../../../decomp/1.9/crimsonland/crimsonland/console_cmd_set_resource_paq.cpp
NOTE=console-resource-pack-command
