IMAGE=grim.dll
FUNCTION=d3dx_jpeg_sep_upsample
COMPILER=msvc7.0
SYMBOL=sep_upsample
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdsample.c
NOTE=ijg-6a-d3dx-separate-upsampling-controller
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
