IMAGE=grim.dll
FUNCTION=d3dx_jpeg_process_data_simple_main
COMPILER=msvc7.0
SYMBOL=process_data_simple_main
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmainct.c
NOTE=ijg-6a-d3dx-context-free-main-controller
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
RECOVERY=semantic-complete
RESIDUAL=compiler
