IMAGE=grim.dll
FUNCTION=d3dx_jpeg_init_master_decompress
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\jdmaster.obj'
REFERENCE_ALIASES='?prepare_for_output_pass@D3DX@@YAXPAUjpeg_decompress_struct@1@@Z:d3dx_jpeg_prepare_for_output_pass,?finish_output_pass@D3DX@@YAXPAUjpeg_decompress_struct@1@@Z:d3dx_jpeg_finish_output_pass,?master_selection@D3DX@@YAXPAUjpeg_decompress_struct@1@@Z:d3dx_jpeg_master_selection'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?jinit_master_decompress@D3DX@@YAXPAUjpeg_decompress_struct@1@@Z'
NOTE=directx-8.1-archive-d3dx-jpeg-init-master-decompress
