from __future__ import annotations

"""
Weapon table extracted from FUN_004519b0.

Generated by scripts/extract_weapon_table.py.
"""

from dataclasses import dataclass
import struct

BASE_ADDR = 0x4D7A2C
STRIDE_BYTES = 0x7C
FIELD_COUNT = 0x1F

FIRE_RATE_OFFSET = 0x48
RELOAD_TIME_OFFSET = 0x4C
SPREAD_OFFSET = 0x50
PROJECTILE_TYPE_OFFSET = 0x6C
DAMAGE_MULT_OFFSET = 0x70

FIELD_OFFSETS = {
    "fire_rate": FIRE_RATE_OFFSET,
    "reload_time": RELOAD_TIME_OFFSET,
    "spread": SPREAD_OFFSET,
    "projectile_type": PROJECTILE_TYPE_OFFSET,
    "damage_mult": DAMAGE_MULT_OFFSET,
}


@dataclass(frozen=True)
class Value:
    raw: str
    number: int | float | None

    def as_int(self) -> int | None:
        if isinstance(self.number, int):
            return self.number
        if isinstance(self.number, float):
            return int(self.number)
        return None

    def as_float(self) -> float | None:
        if isinstance(self.number, float):
            return self.number
        if isinstance(self.number, int):
            raw = self.number & 0xFFFFFFFF
            return struct.unpack("<f", raw.to_bytes(4, "little"))[0]
        return None


@dataclass(frozen=True)
class WeaponEntry:
    weapon_id: int
    name: str | None
    fields: dict[int, Value]

    def value_at(self, offset: int) -> Value | None:
        return self.fields.get(offset)

    @property
    def fire_rate(self) -> float | None:
        value = self.value_at(FIRE_RATE_OFFSET)
        return value.as_float() if value else None

    @property
    def reload_time(self) -> float | None:
        value = self.value_at(RELOAD_TIME_OFFSET)
        return value.as_float() if value else None

    @property
    def spread(self) -> float | None:
        value = self.value_at(SPREAD_OFFSET)
        return value.as_float() if value else None

    @property
    def projectile_type(self) -> int | None:
        value = self.value_at(PROJECTILE_TYPE_OFFSET)
        return value.as_int() if value else None

    @property
    def damage_mult(self) -> float | None:
        value = self.value_at(DAMAGE_MULT_OFFSET)
        return value.as_float() if value else None


WEAPON_TABLE = [
    WeaponEntry(
        weapon_id=-1,
        name=None,
        fields={
            0x64: Value(raw="0", number=0),
        },
    ),
    WeaponEntry(
        weapon_id=0,
        name="Pistol",
        fields={
            0x44: Value(raw="0xc", number=12),
            0x48: Value(raw="0x3f3631f9", number=1060516345),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3e6147ae", number=1046562734),
            0x58: Value(raw="DAT_004c3f78", number=None),
            0x60: Value(raw="DAT_004c3f7c", number=None),
            0x68: Value(raw="5", number=5),
            0x6C: Value(raw="0x425c0000", number=1113325568),
            0x70: Value(raw="0x40833333", number=1082340147),
        },
    ),
    WeaponEntry(
        weapon_id=1,
        name="Assault Rifle",
        fields={
            0x44: Value(raw="0x19", number=25),
            0x48: Value(raw="0x3def9db2", number=1039113650),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3db851ec", number=1035489772),
            0x58: Value(raw="DAT_004c3f88", number=None),
            0x60: Value(raw="DAT_004c3f8c", number=None),
            0x68: Value(raw="1", number=1),
            0x6C: Value(raw="0x42480000", number=1112014848),
        },
    ),
    WeaponEntry(
        weapon_id=2,
        name=None,
        fields={
            0x44: Value(raw="0xc", number=12),
            0x48: Value(raw="0x3f59999a", number=1062836634),
            0x4C: Value(raw="0x3ff33333", number=1072902963),
            0x50: Value(raw="0x3e8a3d71", number=1049247089),
            0x58: Value(raw="DAT_004c3f80", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="1", number=1),
            0x6C: Value(raw="0x42700000", number=1114636288),
            0x70: Value(raw="0x3f99999a", number=1067030938),
            0x74: Value(raw="0xc", number=12),
        },
    ),
    WeaponEntry(
        weapon_id=3,
        name="Sawed-off Shotgun",
        fields={
            0x44: Value(raw="0xc", number=12),
            0x48: Value(raw="0x3f5eb852", number=1063172178),
            0x4C: Value(raw="0x3ff33333", number=1072902963),
            0x50: Value(raw="0x3e051eb8", number=1040522936),
            0x58: Value(raw="_DAT_004d8434", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="1", number=1),
            0x74: Value(raw="0xc", number=12),
        },
    ),
    WeaponEntry(
        weapon_id=4,
        name="Submachine Gun",
        fields={
            0x44: Value(raw="0x1e", number=30),
            0x48: Value(raw="0x3db476b0", number=1035237040),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3da7ef9e", number=1034416030),
            0x58: Value(raw="DAT_004c3f98", number=None),
            0x60: Value(raw="_DAT_004d83c0", number=None),
            0x68: Value(raw="5", number=5),
        },
    ),
    WeaponEntry(
        weapon_id=5,
        name="Gauss Gun",
        fields={
            0x44: Value(raw="6", number=6),
            0x48: Value(raw="0x3f19999a", number=1058642330),
            0x4C: Value(raw="0x3fcccccd", number=1070386381),
            0x50: Value(raw="0x3ed70a3d", number=1054280253),
            0x58: Value(raw="DAT_004c3f90", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="1", number=1),
            0x6C: Value(raw="0x43570000", number=1129775104),
        },
    ),
    WeaponEntry(
        weapon_id=6,
        name="Mean Minigun",
        fields={
            0x44: Value(raw="0x78", number=120),
            0x48: Value(raw="0x3db851ec", number=1035489772),
            0x4C: Value(raw="0x40800000", number=1082130432),
            0x50: Value(raw="0x3d7df3b6", number=1031664566),
            0x58: Value(raw="DAT_004c3f88", number=None),
            0x60: Value(raw="_DAT_004d83c0", number=None),
            0x68: Value(raw="3", number=3),
            0x78: Value(raw="1", number=1),
        },
    ),
    WeaponEntry(
        weapon_id=7,
        name="Flamethrower",
        fields={
            0x44: Value(raw="0x1e", number=30),
            0x48: Value(raw="0x3c04ec63", number=1006955619),
            0x4C: Value(raw="0x40000000", number=1073741824),
            0x50: Value(raw="0x3c75c28f", number=1014350479),
            0x58: Value(raw="DAT_004c3fac", number=None),
            0x5C: Value(raw="2", number=2),
            0x60: Value(raw="_DAT_004d83c0", number=None),
            0x68: Value(raw="8", number=8),
        },
    ),
    WeaponEntry(
        weapon_id=8,
        name="Plasma Rifle",
        fields={
            0x44: Value(raw="0x14", number=20),
            0x48: Value(raw="0x3e94e545", number=1049945413),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3e3a5e35", number=1044012597),
            0x58: Value(raw="DAT_004c3f9c", number=None),
            0x60: Value(raw="_DAT_004d83c0", number=None),
            0x6C: Value(raw="0x41f00000", number=1106247680),
            0x70: Value(raw="0x40a00000", number=1084227584),
        },
    ),
    WeaponEntry(
        weapon_id=9,
        name="Multi-Plasma",
        fields={
            0x44: Value(raw="8", number=8),
            0x48: Value(raw="0x3f1eed84", number=1058991492),
            0x4C: Value(raw="0x3fb33333", number=1068708659),
            0x50: Value(raw="0x3ea3d70a", number=1050924810),
            0x58: Value(raw="DAT_004c3f9c", number=None),
            0x60: Value(raw="_DAT_004d83c0", number=None),
            0x74: Value(raw="3", number=3),
        },
    ),
    WeaponEntry(
        weapon_id=10,
        name="Plasma Minigun",
        fields={
            0x44: Value(raw="0x1e", number=30),
            0x48: Value(raw="0x3de147ae", number=1038174126),
            0x4C: Value(raw="0x3fa66666", number=1067869798),
            0x50: Value(raw="0x3dc6a7f0", number=1036429296),
            0x58: Value(raw="DAT_004c3fa0", number=None),
            0x60: Value(raw="_DAT_004d83c0", number=None),
            0x6C: Value(raw="0x420c0000", number=1108082688),
            0x70: Value(raw="0x40066666", number=1074161254),
            0x78: Value(raw="2", number=2),
        },
    ),
    WeaponEntry(
        weapon_id=11,
        name="Rocket Launcher",
        fields={
            0x44: Value(raw="5", number=5),
            0x48: Value(raw="0x3f3da5d6", number=1061004758),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3ed70a3d", number=1054280253),
            0x58: Value(raw="DAT_004c3fc0", number=None),
            0x60: Value(raw="DAT_004c3fc8", number=None),
            0x68: Value(raw="8", number=8),
            0x78: Value(raw="2", number=2),
        },
    ),
    WeaponEntry(
        weapon_id=12,
        name="Seeker Rockets",
        fields={
            0x44: Value(raw="8", number=8),
            0x48: Value(raw="0x3e9f22b6", number=1050616502),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3ea3d70a", number=1050924810),
            0x58: Value(raw="DAT_004c3fc0", number=None),
            0x60: Value(raw="DAT_004c3fc8", number=None),
            0x68: Value(raw="8", number=8),
        },
    ),
    WeaponEntry(
        weapon_id=13,
        name="Plasma Shotgun",
        fields={
            0x44: Value(raw="8", number=8),
            0x48: Value(raw="0x3ef5c28f", number=1056293519),
            0x4C: Value(raw="0x40466666", number=1078355558),
            0x50: Value(raw="0x3de147ae", number=1038174126),
            0x58: Value(raw="DAT_004c3fa4", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x74: Value(raw="0xe", number=14),
            0x78: Value(raw="1", number=1),
        },
    ),
    WeaponEntry(
        weapon_id=14,
        name="Blow Torch",
        fields={
            0x44: Value(raw="0x1e", number=30),
            0x48: Value(raw="0x3bc84f90", number=1002983312),
            0x4C: Value(raw="0x3fc00000", number=1069547520),
            0x50: Value(raw="0x3c23d70a", number=1008981770),
            0x58: Value(raw="DAT_004c3fac", number=None),
            0x5C: Value(raw="2", number=2),
            0x60: Value(raw="_DAT_004d83c0", number=None),
            0x68: Value(raw="8", number=8),
            0x78: Value(raw="1", number=1),
        },
    ),
    WeaponEntry(
        weapon_id=15,
        name="HR Flamer",
        fields={
            0x44: Value(raw="0x1e", number=30),
            0x48: Value(raw="0x3c0b4396", number=1007371158),
            0x4C: Value(raw="0x3fe66666", number=1072064102),
            0x50: Value(raw="0x3c23d70a", number=1008981770),
            0x58: Value(raw="DAT_004c3fac", number=None),
            0x5C: Value(raw="2", number=2),
            0x60: Value(raw="_DAT_004d83c0", number=None),
            0x68: Value(raw="8", number=8),
            0x78: Value(raw="2", number=2),
        },
    ),
    WeaponEntry(
        weapon_id=16,
        name="Mini-Rocket Swarmers",
        fields={
            0x44: Value(raw="5", number=5),
            0x48: Value(raw="0x3fe66666", number=1072064102),
            0x4C: Value(raw="0x3fe66666", number=1072064102),
            0x50: Value(raw="0x3df5c28f", number=1039516303),
            0x58: Value(raw="DAT_004c3fc0", number=None),
            0x60: Value(raw="DAT_004c3fc8", number=None),
            0x68: Value(raw="8", number=8),
            0x78: Value(raw="2", number=2),
        },
    ),
    WeaponEntry(
        weapon_id=17,
        name="Rocket Minigun",
        fields={
            0x44: Value(raw="0x10", number=16),
            0x48: Value(raw="0x3df5c28f", number=1039516303),
            0x4C: Value(raw="0x3fe66666", number=1072064102),
            0x50: Value(raw="0x3df5c28f", number=1039516303),
            0x58: Value(raw="DAT_004c3fc4", number=None),
            0x60: Value(raw="DAT_004c3fc8", number=None),
            0x68: Value(raw="8", number=8),
            0x78: Value(raw="3", number=3),
        },
    ),
    WeaponEntry(
        weapon_id=18,
        name="Pulse Gun",
        fields={
            0x44: Value(raw="0x10", number=16),
            0x48: Value(raw="0x3dcccccd", number=1036831949),
            0x4C: Value(raw="0x3dcccccd", number=1036831949),
            0x50: Value(raw="0", number=0),
            0x58: Value(raw="DAT_004c3fa8", number=None),
            0x60: Value(raw="DAT_004c3f8c", number=None),
            0x68: Value(raw="8", number=8),
            0x6C: Value(raw="0x41a00000", number=1101004800),
            0x70: Value(raw="0x3f800000", number=1065353216),
        },
    ),
    WeaponEntry(
        weapon_id=19,
        name="Jackhammer",
        fields={
            0x44: Value(raw="0x10", number=16),
            0x48: Value(raw="0x3e0f5c29", number=1041194025),
            0x4C: Value(raw="0x40400000", number=1077936128),
            0x50: Value(raw="0x3e23d70a", number=1042536202),
            0x58: Value(raw="DAT_004c3f80", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="1", number=1),
            0x74: Value(raw="4", number=4),
            0x78: Value(raw="4", number=4),
        },
    ),
    WeaponEntry(
        weapon_id=20,
        name="Ion Rifle",
        fields={
            0x44: Value(raw="8", number=8),
            0x48: Value(raw="0x3ecccccd", number=1053609165),
            0x4C: Value(raw="0x3faccccd", number=1068289229),
            0x50: Value(raw="0x3de56042", number=1038442562),
            0x58: Value(raw="DAT_004c3fb4", number=None),
            0x60: Value(raw="_DAT_004d86a8", number=None),
            0x68: Value(raw="8", number=8),
            0x6C: Value(raw="0x41700000", number=1097859072),
            0x70: Value(raw="0x40400000", number=1077936128),
            0x78: Value(raw="4", number=4),
        },
    ),
    WeaponEntry(
        weapon_id=21,
        name="Ion Minigun",
        fields={
            0x44: Value(raw="0x14", number=20),
            0x48: Value(raw="0x3dcccccd", number=1036831949),
            0x4C: Value(raw="0x3fe66666", number=1072064102),
            0x50: Value(raw="0x3db851ec", number=1035489772),
            0x58: Value(raw="DAT_004c3fb8", number=None),
            0x60: Value(raw="_DAT_004d86a8", number=None),
            0x68: Value(raw="8", number=8),
            0x6C: Value(raw="0x41a00000", number=1101004800),
            0x70: Value(raw="0x3fb33333", number=1068708659),
            0x78: Value(raw="4", number=4),
        },
    ),
    WeaponEntry(
        weapon_id=22,
        name="Ion Cannon",
        fields={
            0x44: Value(raw="3", number=3),
            0x48: Value(raw="0x3f800000", number=1065353216),
            0x4C: Value(raw="0x40400000", number=1077936128),
            0x50: Value(raw="0x3f2e147b", number=1059984507),
            0x58: Value(raw="DAT_004c3fb4", number=None),
            0x60: Value(raw="_DAT_004d86a8", number=None),
            0x6C: Value(raw="0x41200000", number=1092616192),
            0x70: Value(raw="0x4185999a", number=1099274650),
        },
    ),
    WeaponEntry(
        weapon_id=23,
        name="Shrinkifier 5k",
        fields={
            0x44: Value(raw="8", number=8),
            0x48: Value(raw="0x3e570a3d", number=1045891645),
            0x4C: Value(raw="0x3f9c28f6", number=1067198710),
            0x50: Value(raw="0x3d23d70a", number=1025758986),
            0x58: Value(raw="DAT_004c3fb4", number=None),
            0x60: Value(raw="_DAT_004d86a8", number=None),
            0x64: Value(raw="0x17", number=23),
            0x68: Value(raw="8", number=8),
            0x70: Value(raw="0", number=0),
        },
    ),
    WeaponEntry(
        weapon_id=24,
        name="Blade Gun",
        fields={
            0x44: Value(raw="6", number=6),
            0x48: Value(raw="0x3eb33333", number=1051931443),
            0x4C: Value(raw="0x40600000", number=1080033280),
            0x50: Value(raw="0x3d23d70a", number=1025758986),
            0x58: Value(raw="DAT_004c3fb4", number=None),
            0x60: Value(raw="DAT_004c3fbc", number=None),
            0x64: Value(raw="0x18", number=24),
            0x68: Value(raw="8", number=8),
            0x6C: Value(raw="0x41a00000", number=1101004800),
            0x70: Value(raw="0x41300000", number=1093664768),
        },
    ),
    WeaponEntry(
        weapon_id=25,
        name="Spider Plasma",
        fields={
            0x44: Value(raw="5", number=5),
            0x48: Value(raw="0x3e4ccccd", number=1045220557),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3d23d70a", number=1025758986),
            0x58: Value(raw="_DAT_004d92bc", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="8", number=8),
            0x6C: Value(raw="0x41200000", number=1092616192),
            0x70: Value(raw="0x3f000000", number=1056964608),
            0x78: Value(raw="4", number=4),
        },
    ),
    WeaponEntry(
        weapon_id=26,
        name="Evil Scythe",
        fields={
            0x44: Value(raw="3", number=3),
            0x48: Value(raw="0x3f800000", number=1065353216),
            0x4C: Value(raw="0x40400000", number=1077936128),
            0x50: Value(raw="0x3f2e147b", number=1059984507),
            0x58: Value(raw="DAT_004c3fb4", number=None),
            0x60: Value(raw="_DAT_004d86a8", number=None),
            0x64: Value(raw="0x19", number=25),
        },
    ),
    WeaponEntry(
        weapon_id=27,
        name="Plasma Cannon",
        fields={
            0x44: Value(raw="3", number=3),
            0x48: Value(raw="0x3f666666", number=1063675494),
            0x4C: Value(raw="0x402ccccd", number=1076677837),
            0x50: Value(raw="0x3f19999a", number=1058642330),
            0x58: Value(raw="DAT_004c3f9c", number=None),
            0x60: Value(raw="_DAT_004d86a8", number=None),
            0x64: Value(raw="0x19", number=25),
            0x6C: Value(raw="0x41200000", number=1092616192),
            0x70: Value(raw="0x41e00000", number=1105199104),
            0x78: Value(raw="0", number=0),
        },
    ),
    WeaponEntry(
        weapon_id=28,
        name="Splitter Gun",
        fields={
            0x44: Value(raw="6", number=6),
            0x48: Value(raw="0x3f333333", number=1060320051),
            0x4C: Value(raw="0x400ccccd", number=1074580685),
            0x50: Value(raw="0x3e8f5c29", number=1049582633),
            0x58: Value(raw="DAT_004c3fb4", number=None),
            0x60: Value(raw="_DAT_004d86a8", number=None),
            0x6C: Value(raw="0x41f00000", number=1106247680),
            0x70: Value(raw="0x40c00000", number=1086324736),
            0x78: Value(raw="0", number=0),
        },
    ),
    WeaponEntry(
        weapon_id=29,
        name="Gauss Shotgun",
        fields={
            0x44: Value(raw="4", number=4),
            0x48: Value(raw="0x3f866666", number=1065772646),
            0x4C: Value(raw="0x40066666", number=1074161254),
            0x50: Value(raw="0x3e8a3d71", number=1049247089),
            0x58: Value(raw="DAT_004c3f90", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x64: Value(raw="0x1e", number=30),
            0x68: Value(raw="1", number=1),
            0x78: Value(raw="4", number=4),
        },
    ),
    WeaponEntry(
        weapon_id=30,
        name="Ion Shotgun",
        fields={
            0x44: Value(raw="10", number=10),
            0x48: Value(raw="0x3f59999a", number=1062836634),
            0x4C: Value(raw="0x3ff33333", number=1072902963),
            0x50: Value(raw="0x3e8a3d71", number=1049247089),
            0x58: Value(raw="DAT_004c3fb4", number=None),
            0x60: Value(raw="_DAT_004d86a8", number=None),
            0x64: Value(raw="0x1f", number=31),
            0x68: Value(raw="1", number=1),
            0x74: Value(raw="8", number=8),
            0x78: Value(raw="4", number=4),
        },
    ),
    WeaponEntry(
        weapon_id=31,
        name="Flameburst",
        fields={
            0x44: Value(raw="0x3c", number=60),
            0x48: Value(raw="0x3ca3d70a", number=1017370378),
            0x4C: Value(raw="0x40400000", number=1077936128),
            0x50: Value(raw="0x3e3851ec", number=1043878380),
            0x58: Value(raw="DAT_004c3fac", number=None),
            0x60: Value(raw="_DAT_004d86a8", number=None),
            0x64: Value(raw="0x1d", number=29),
            0x78: Value(raw="4", number=4),
        },
    ),
    WeaponEntry(
        weapon_id=32,
        name=None,
        fields={
            0x44: Value(raw="0xc", number=12),
            0x48: Value(raw="0x3f333333", number=1060320051),
            0x4C: Value(raw="0x40000000", number=1073741824),
            0x50: Value(raw="0x3ec28f5c", number=1052938076),
            0x58: Value(raw="DAT_004c3fb4", number=None),
            0x60: Value(raw="_DAT_004d86a8", number=None),
            0x64: Value(raw="0x1e", number=30),
        },
    ),
    WeaponEntry(
        weapon_id=40,
        name="Plague Sphreader Gun",
        fields={
            0x44: Value(raw="5", number=5),
            0x48: Value(raw="0x3e4ccccd", number=1045220557),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3d23d70a", number=1025758986),
            0x58: Value(raw="DAT_004c4028", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="8", number=8),
            0x6C: Value(raw="0x41700000", number=1097859072),
            0x70: Value(raw="0", number=0),
        },
    ),
    WeaponEntry(
        weapon_id=41,
        name="Bubblegun",
        fields={
            0x44: Value(raw="0xf", number=15),
            0x48: Value(raw="0x3e252bd4", number=1042623444),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3d4ccccd", number=1028443341),
            0x58: Value(raw="_DAT_004d92bc", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="8", number=8),
        },
    ),
    WeaponEntry(
        weapon_id=42,
        name="Rainbow Gun",
        fields={
            0x44: Value(raw="10", number=10),
            0x48: Value(raw="0x3e4ccccd", number=1045220557),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3db851ec", number=1035489772),
            0x58: Value(raw="_DAT_004d92bc", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="8", number=8),
            0x6C: Value(raw="0x41200000", number=1092616192),
        },
    ),
    WeaponEntry(
        weapon_id=43,
        name="Grim Weapon",
        fields={
            0x44: Value(raw="3", number=3),
            0x48: Value(raw="0x3f000000", number=1056964608),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3ecccccd", number=1053609165),
            0x58: Value(raw="_DAT_004d92bc", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
        },
    ),
    WeaponEntry(
        weapon_id=44,
        name="Fire bullets",
        fields={
            0x44: Value(raw="0x70", number=112),
            0x48: Value(raw="0x3e0f5c29", number=1041194025),
            0x4C: Value(raw="0x3f99999a", number=1067030938),
            0x50: Value(raw="0x3e6147ae", number=1046562734),
            0x58: Value(raw="_DAT_004d7b7c", number=None),
            0x60: Value(raw="DAT_004c3f7c", number=None),
            0x68: Value(raw="1", number=1),
            0x6C: Value(raw="0x42700000", number=1114636288),
            0x70: Value(raw="0x3e800000", number=1048576000),
        },
    ),
    WeaponEntry(
        weapon_id=49,
        name="Transmutator",
        fields={
            0x44: Value(raw="0x32", number=50),
            0x48: Value(raw="0x3d23d70a", number=1025758986),
            0x4C: Value(raw="0x40a00000", number=1084227584),
            0x50: Value(raw="0x3d23d70a", number=1025758986),
            0x58: Value(raw="DAT_004c4028", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="9", number=9),
        },
    ),
    WeaponEntry(
        weapon_id=50,
        name="Blaster R-300",
        fields={
            0x44: Value(raw="0x14", number=20),
            0x48: Value(raw="0x3da3d70a", number=1034147594),
            0x4C: Value(raw="0x40000000", number=1073741824),
            0x50: Value(raw="0x3d4ccccd", number=1028443341),
            0x58: Value(raw="DAT_004c3f9c", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="9", number=9),
        },
    ),
    WeaponEntry(
        weapon_id=51,
        name="`=Lighting Rifle",
        fields={
            0x44: Value(raw="500", number=500),
            0x48: Value(raw="0x40800000", number=1082130432),
            0x4C: Value(raw="0x41000000", number=1090519040),
            0x50: Value(raw="0x3f800000", number=1065353216),
            0x58: Value(raw="DAT_004c3ff0", number=None),
            0x60: Value(raw="DAT_004c3f84", number=None),
            0x68: Value(raw="8", number=8),
        },
    ),
    WeaponEntry(
        weapon_id=52,
        name="Nuke Launcher",
        fields={
            0x44: Value(raw="1", number=1),
            0x48: Value(raw="0x40800000", number=1082130432),
            0x4C: Value(raw="0x41000000", number=1090519040),
            0x50: Value(raw="0x3f800000", number=1065353216),
            0x58: Value(raw="_DAT_004d93b4", number=None),
            0x60: Value(raw="_DAT_004d93bc", number=None),
            0x68: Value(raw="8", number=8),
        },
    ),
]

WEAPON_BY_ID = {entry.weapon_id: entry for entry in WEAPON_TABLE}

WEAPON_BY_NAME = {entry.name: entry for entry in WEAPON_TABLE if entry.name is not None}
