IMAGE=crimsonland.exe
FUNCTION=ui_menu_main_click_statistics
SYMBOL=ui_menu_main_click_statistics
SOURCE=../../../../decomp/1.9/crimsonland/ui_elements/ui_menu_main_click_statistics.cpp
NOTE=ui-menu-statistics-audio
