IMAGE=crimsonland.exe
FUNCTION=console_cmd_snd_add_game_tune
SYMBOL=console_cmd_snd_add_game_tune
SOURCE=../../../../decomp/1.9/crimsonland/crimsonland/console_cmd_snd_add_game_tune.cpp
NOTE=console-music-queue-command
