IMAGE=grim.dll
FUNCTION=png_destroy_struct
COMPILER=msvc7.0
SYMBOL=grim_png_destroy_struct
SOURCE=../../shared/grim_png_callbacks.cpp
NOTE=png-destroy-struct
CFLAGS="/O1 /G6 /W3 /GR- /MD"
REFERENCE_ALIASES='free:free'
