IMAGE=grim.dll
FUNCTION=grim_jpeg_consume_coefficients
SYMBOL=consume_data
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdcoefct.c
NOTE=ijg-6a-stock-coefficient-consumer
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
