IMAGE=grim.dll
FUNCTION=d3dx_jpeg_access_virt_sarray
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\jmemmgr.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?access_virt_sarray@D3DX@@YAPAPAEPAUjpeg_common_struct@1@PAUjvirt_sarray_control@1@IIE@Z'
REFERENCE_ALIASES='?do_sarray_io@D3DX@@YAXPAUjpeg_common_struct@1@PAUjvirt_sarray_control@1@E@Z:d3dx_jpeg_do_sarray_io,?jzero_far@D3DX@@YAXPAXI@Z:d3dx_jpeg_zero_far'
NOTE=directx-8.1-archive-ijg-6a-access-virtual-sample-array
