IMAGE=crimsonland.exe
FUNCTION=console_cmd_generate_terrain
SYMBOL=console_cmd_generate_terrain
SOURCE=../../../../decomp/1.9/crimsonland/crimsonland/console_cmd_generate_terrain.cpp
NOTE=console-terrain-generation-command
