IMAGE=grim.dll
FUNCTION=d3dx_jpeg_initial_setup
COMPILER=msvc7.0
SYMBOL=initial_setup
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdinput.c
NOTE=ijg-6a-d3dx-initial-input-setup
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
RECOVERY=semantic-complete
RESIDUAL=compiler
