IMAGE=grim.dll
FUNCTION=inflate_codes_new
COMPILER=msvc7.0
SYMBOL=grim_inflate_codes_new
SOURCE=../../shared/grim_zlib_blocks_source.c
NOTE=zlib-1.1.3-inflate-code-state-allocation
CFLAGS="/O1 /G6 /W3 /GR- /MD"
