IMAGE=grim.dll
FUNCTION=d3dx_image_jpeg_error_exit
END=0x10010dec
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\cd3dximage.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?d3dx_jpeg_error_exit@@YAXPAUjpeg_common_struct@D3DX@@@Z'
NOTE=directx-8.1-archive-cd3dximage-jpeg-error-exit-with-unreachable-pop
