IMAGE=grim.dll
FUNCTION=d3dx_find_closest_device_format
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\d3dx8tex.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?D3DXFindClosestDeviceFormat@@YA?AW4_D3DFORMAT@@PAUIDirect3DDevice8@@KW4_D3DRESOURCETYPE@@PBU_D3DXFORMAT_INFO@@@Z'
NOTE=directx-8.1-archive-find-closest-device-format
