IMAGE=grim.dll
FUNCTION=0x1003154e
COMPILER=msvc7.0
SYMBOL=grim_jpeg_h2v1_fancy_upsample
SOURCE=../../shared/grim_jpeg_source_helpers.cpp
NOTE=ijg-horizontal-two-to-one-triangle-upsampler
CFLAGS="/O1 /G6 /W3 /GR- /MD"
