IMAGE=grim.dll
FUNCTION=d3dx_jpeg_select_component_color_counts
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\jquant1.obj'
REFERENCE_ALIASES='?RGB_order@?1??select_ncolors@D3DX@@YAHPAUjpeg_decompress_struct@2@QAH@Z@4QBHB:d3dx_jpeg_quant1_rgb_order'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?select_ncolors@D3DX@@YAHPAUjpeg_decompress_struct@1@QAH@Z'
NOTE=directx-8.1-archive-d3dx-jpeg-select-component-color-counts
