IMAGE=grim.dll
FUNCTION=d3dx_jpeg_free_pool
COMPILER=msvc6.5pp
SYMBOL=free_pool
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jmemmgr.c
NOTE=ijg-6a-d3dx-memory-pool-release
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='jpeg_free_large:zcfree,jpeg_free_small:zcfree'
