IMAGE=crimsonland.exe
FUNCTION=highscore_sync_worker
SYMBOL=highscore_sync_worker
SOURCE=../../../../decomp/1.9/crimsonland/crimsonland/highscore_sync_worker.cpp
NOTE=online-highscore-submit-receive-worker
