IMAGE=grim.dll
FUNCTION=d3dx_jpeg_start_pass_main
COMPILER=msvc7.0
SYMBOL=start_pass_main
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmainct.c
NOTE=ijg-6a-d3dx-main-controller-pass-initializer
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='process_data_context_main:d3dx_jpeg_process_data_context_main,make_funny_pointers:d3dx_jpeg_make_funny_pointers,process_data_simple_main:d3dx_jpeg_process_data_simple_main,process_data_crank_post:d3dx_jpeg_process_data_crank_post'
