IMAGE=grim.dll
FUNCTION=grim_apply_color_key
SYMBOL='?apply_color_key@grim_pixel_format_t@@IAEXPAM@Z'
SOURCE=scratch.cpp
COMPILER=msvc6.5pp
CFLAGS="/O1 /Oi /G6 /W3 /GR-"
NOTE=grim-pixel-format-color-key-mask
