IMAGE=grim.dll
FUNCTION=d3dx_jpeg_post_process_prepass
COMPILER=msvc7.0
SYMBOL=post_process_prepass
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdpostct.c
NOTE=ijg-6a-d3dx-two-pass-quantizer-prepass
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
