IMAGE=grim.dll
FUNCTION=0x10032055
COMPILER=msvc6.5
SYMBOL=grim_jpeg_start_pass_merged_upsample
SOURCE=../../shared/grim_jpeg_source_helpers.cpp
NOTE=ijg-start-pass-merged-upsample
CFLAGS="/O1 /G6 /W3 /GR- /MD"
