IMAGE=grim.dll
FUNCTION=0x10033975
COMPILER=msvc7.0
SYMBOL=grim_jpeg_color_quantize3
SOURCE=../../shared/grim_jpeg_quant1_source.c
NOTE=ijg-three-component-one-pass-color-quantizer
CFLAGS="/O1 /G6 /W3 /GR- /MD"
