IMAGE=grim.dll
FUNCTION=d3dx_jpeg_reset_input_controller
COMPILER=msvc6.5
SYMBOL=reset_input_controller
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdinput.c
NOTE=ijg-6a-d3dx-input-controller-reset
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='consume_markers:d3dx_jpeg_consume_markers'
