IMAGE=grim.dll
FUNCTION=0x1001ed89
COMPILER=msvc7.0
SYMBOL=grim_png_read_transform_info
SOURCE=../../shared/grim_png_source_helpers.cpp
NOTE=libpng-1.0.5-read-transform-info
CFLAGS="/O1 /G6 /W3 /GR- /MD"
