IMAGE=grim.dll
FUNCTION=0x10032bae
COMPILER=msvc7.0
SYMBOL=grim_jpeg_find_nearby_colors
SOURCE=../../shared/grim_jpeg_quant2_source.c
NOTE=ijg-two-pass-inverse-map-candidate-selector
CFLAGS="/O1 /G6 /W3 /GR- /MD"
