IMAGE=grim.dll
FUNCTION=d3dx_jpeg_init_color_deconverter
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\jdcolor.obj'
REFERENCE_ALIASES='?start_pass_dcolor@D3DX@@YAXPAUjpeg_decompress_struct@1@@Z:grim_jpeg_source_noop,?grayscale_convert@D3DX@@YAXPAUjpeg_decompress_struct@1@PAPAPAEIPAPAEH@Z:d3dx_jpeg_grayscale_convert,?ycc_rgb_convert@D3DX@@YAXPAUjpeg_decompress_struct@1@PAPAPAEIPAPAEH@Z:d3dx_jpeg_ycc_rgb_convert,?build_ycc_rgb_table@D3DX@@YAXPAUjpeg_decompress_struct@1@@Z:d3dx_jpeg_build_ycc_rgb_table,?null_convert@D3DX@@YAXPAUjpeg_decompress_struct@1@PAPAPAEIPAPAEH@Z:d3dx_jpeg_null_convert,?ycck_cmyk_convert@D3DX@@YAXPAUjpeg_decompress_struct@1@PAPAPAEIPAPAEH@Z:d3dx_jpeg_ycck_cmyk_convert'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?jinit_color_deconverter@D3DX@@YAXPAUjpeg_decompress_struct@1@@Z'
NOTE=directx-8.1-archive-d3dx-jpeg-init-color-deconverter
