IMAGE=crimsonland.exe
FUNCTION=mod_api_gfx_set_blend_mode
SYMBOL=?mod_api_gfx_set_blend_mode@mod_api_cpp_t@@UAEXHH@Z
SOURCE=../../../../decomp/1.9/crimsonland/mods/mod_api_gfx_set_blend_mode.cpp
NOTE=mod-api-graphics-blend-mode
