IMAGE=grim.dll
FUNCTION=grim_pixel_format_scalar_deleting_destroy_yuv_base
SYMBOL='??_Ggrim_pixel_format_yuv_t@@UAEPAXI@Z'
SOURCE=scratch.cpp
COMPILER=msvc6.5pp
CFLAGS="/O1 /Oi /G6 /Ob0 /W3 /GR- /GX"
REFERENCE_ALIASES='??1grim_pixel_format_yuv_t@@UAE@XZ:grim_pixel_format_destroy_yuv'
NOTE=grim-yuv-base-scalar-deleting-destructor
