IMAGE=grim.dll
FUNCTION=grim_pixel_format_ctor_r3g3b2
SYMBOL='??0grim_pixel_format_r3g3b2_t@@QAE@PAI@Z'
SOURCE=scratch.cpp
COMPILER=msvc6.5pp
CFLAGS="/O1 /Oi /G6 /W3 /GR-"
REFERENCE_ALIASES='??0grim_pixel_format_base_t@@QAE@PAIII@Z:grim_pixel_format_init,??_7grim_pixel_format_r3g3b2_t@@6B@:grim_pixel_format_vtable_r3g3b2'
NOTE=grim-pixel-format-r3g3b2-constructor
