IMAGE=crimsonland.exe
FUNCTION=mod_api_gfx_set_subset
SYMBOL=?mod_api_gfx_set_subset@mod_api_cpp_t@@UAEXMMMM@Z
SOURCE=../../../../decomp/1.9/crimsonland/mods/mod_api_gfx_set_subset.cpp
NOTE=mod-api-graphics-uv-subset
