IMAGE=crimsonland.exe
FUNCTION=crt_heap_init
ARCHIVE=../../../native/providers/build/vc6-sp6/vc98/lib/libcmt.lib
ARCHIVE_MEMBER='build\intel\mt_obj\heapinit.obj'
ARCHIVE_SHA256=a541c95e5ffdd6d5573d1976f5e5d0038f2c4fb0bcb02975c68948bf1d6e452a
SYMBOL=__heap_init
REFERENCE_ALIASES=___active_heap:crt_heap_mode,___heap_select:crt_heap_select,___old_sbh_new_region:crt_sbh_create_region,___sbh_heap_init:crt_sbh_init,__crtheap:crt_heap_handle
NOTE=vc6-sp6-libcmt-crt-heap-init
