IMAGE=grim.dll
FUNCTION=grim_jpeg_new_color_map_1_quant
SYMBOL=new_color_map_1_quant
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jquant1.c
NOTE=ijg-6a-stock-one-pass-mode-change-error
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
