IMAGE=grim.dll
FUNCTION=jpeg_start_decompress
SYMBOL=jpeg_start_decompress
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdapistd.c
NOTE=ijg-6a-stock-start-decompress
CFLAGS='/O2 /GB /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
