IMAGE=crimsonland.exe
FUNCTION=vorbis_mem_close_callback
SYMBOL=vorbis_mem_close_callback
SOURCE=../../../../decomp/1.9/crimsonland/platform/vorbis_mem_close_callback.cpp
NOTE=vorbis-memory-close-callback
