IMAGE=grim.dll
FUNCTION=x3d_acos
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='.\Release\math.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='_a_acos'
REFERENCE_ALIASES='sgn:d3dx_x87_math_sign,mabs:d3dx_x87_math_abs_mask,half:d3dx_x87_math_half,one:d3dx_x87_math_one,bnd:d3dx_x87_math_acos_bound,asq1:d3dx_x87_math_acos_q1,asp1:d3dx_x87_math_acos_p1,asp0:d3dx_x87_math_acos_p0,asq0:d3dx_x87_math_acos_q0,npio2:d3dx_x87_math_negative_pi_over_2,pio2:d3dx_x87_math_pi_over_2,oob:d3dx_x87_math_out_of_bounds'
NOTE=directx-8.1-archive-x87-acos
