IMAGE=grim.dll
FUNCTION=grim_jpeg_open_backing_store
SYMBOL=jpeg_open_backing_store
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jmemnobs.c
NOTE=ijg-6a-stock-open-backing-store
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
