IMAGE=crimsonland.exe
FUNCTION=mod_api_gfx_set_color
SYMBOL=?mod_api_gfx_set_color@mod_api_cpp_t@@UAEXMMMM@Z
SOURCE=../../../../decomp/1.9/crimsonland/mods/mod_api_gfx_set_color.cpp
NOTE=mod-api-graphics-color
