IMAGE=grim.dll
FUNCTION=grim_jpeg_start_input_pass_coef
SYMBOL=start_input_pass
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdcoefct.c
NOTE=ijg-6a-stock-coefficient-input-pass
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
