IMAGE=crimsonland.exe
FUNCTION=sfx_entry_create_buffers
SYMBOL=sfx_entry_create_buffers
SOURCE=../../../../decomp/1.9/crimsonland/sound/sfx_entry_create_buffers.cpp
NOTE=audio-directsound-buffer-create
