IMAGE=grim.dll
FUNCTION=grim_vertex_space_converter_destroy
SYMBOL='??1grim_vertex_space_converter_t@@UAE@XZ'
SOURCE=../../shared/grim_vertex_space_converter.cpp
NOTE=d3dx-vertex-space-converter-destructor
CFLAGS="/O1 /G6 /W3 /GR- /MD"
REFERENCE_ALIASES='??_7grim_vertex_space_converter_t@@6B@:grim_vertex_space_converter_vtable'
