IMAGE=grim.dll
FUNCTION=grim_vertex_space_converter_destroy
SYMBOL='??1grim_vertex_space_converter_t@@UAE@XZ'
SOURCE=scratch.cpp
COMPILER=msvc6.5pp
CFLAGS="/O1 /GB /W3 /GR-"
REFERENCE_ALIASES='??_7grim_vertex_space_converter_t@@6B@:grim_vertex_space_converter_vtable'
NOTE=grim-converted-vertex-buffer-destruction
