IMAGE=grim.dll
FUNCTION=grim_vertex_space_converter_noop
SYMBOL='?noop@grim_vertex_space_converter_t@@QAEXIII@Z'
SOURCE=../../shared/grim_vertex_space_converter.cpp
NOTE=d3dx-vertex-space-converter-noop-leaf
CFLAGS="/O1 /G6 /W3 /GR- /MD"
