IMAGE=grim.dll
FUNCTION=d3dx_jpeg_calc_output_dimensions
COMPILER=msvc7.0
SYMBOL=jpeg_calc_output_dimensions
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmaster.c
NOTE=ijg-6a-d3dx-output-dimensions
CFLAGS='/O1 /Oi /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='jdiv_round_up:jdiv_round_up,use_merged_upsample:d3dx_jpeg_use_merged_upsample'
