IMAGE=grim.dll
FUNCTION=grim_jaz_jpeg_consume_input
SYMBOL=jpeg_consume_input
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdapimin.c
NOTE=ijg-6a-stock-consume-input
CFLAGS='/O2 /GB /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES=default_decompress_parms:grim_jaz_jpeg_default_decompress_parms
