IMAGE=grim.dll
FUNCTION=d3dx_jpeg_get_small
COMPILER=msvc7.0
SYMBOL=jpeg_get_small
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jmemnobs.c
NOTE=ijg-6a-d3dx-small-large-allocation-fold
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
