const std = @import("std");

pub const SfxId = enum {
    trooper_inpain_01,
    trooper_inpain_02,
    trooper_inpain_03,
    trooper_die_01,
    trooper_die_02,
    trooper_die_03,
    zombie_die_01,
    zombie_die_02,
    zombie_die_03,
    zombie_die_04,
    zombie_attack_01,
    zombie_attack_02,
    alien_die_01,
    alien_die_02,
    alien_die_03,
    alien_die_04,
    alien_attack_01,
    alien_attack_02,
    lizard_die_01,
    lizard_die_02,
    lizard_die_03,
    lizard_die_04,
    lizard_attack_01,
    lizard_attack_02,
    spider_die_01,
    spider_die_02,
    spider_die_03,
    spider_die_04,
    spider_attack_01,
    spider_attack_02,
    pistol_fire,
    pistol_reload,
    shotgun_fire,
    shotgun_reload,
    autorifle_fire,
    autorifle_reload,
    gauss_fire,
    hrpm_fire,
    shock_fire,
    plasmaminigun_fire,
    plasmashotgun_fire,
    pulse_fire,
    flamer_fire_01,
    flamer_fire_02,
    shock_reload,
    shock_fire_alt,
    shockminigun_fire,
    rocket_fire,
    rocketmini_fire,
    autorifle_reload_alt,
    bullet_hit_01,
    bullet_hit_02,
    bullet_hit_03,
    bullet_hit_04,
    bullet_hit_05,
    bullet_hit_06,
    shock_hit_01,
    explosion_small,
    explosion_medium,
    explosion_large,
    shockwave,
    questhit,
    ui_bonus,
    ui_buttonclick,
    ui_panelclick,
    ui_levelup,
    ui_typeclick_01,
    ui_typeclick_02,
    ui_typeenter,
    ui_clink_01,
    bloodspill_01,
    bloodspill_02,
};

pub const sfx_id_count = std.meta.fields(SfxId).len;

pub const SfxSpec = struct {
    entry_name: []const u8,
};

pub const native_order = [_]SfxId{
    .trooper_inpain_01,
    .trooper_inpain_02,
    .trooper_inpain_03,
    .trooper_die_01,
    .trooper_die_02,
    .trooper_die_03,
    .zombie_die_01,
    .zombie_die_02,
    .zombie_die_03,
    .zombie_die_04,
    .zombie_attack_01,
    .zombie_attack_02,
    .alien_die_01,
    .alien_die_02,
    .alien_die_03,
    .alien_die_04,
    .alien_attack_01,
    .alien_attack_02,
    .lizard_die_01,
    .lizard_die_02,
    .lizard_die_03,
    .lizard_die_04,
    .lizard_attack_01,
    .lizard_attack_02,
    .spider_die_01,
    .spider_die_02,
    .spider_die_03,
    .spider_die_04,
    .spider_attack_01,
    .spider_attack_02,
    .pistol_fire,
    .pistol_reload,
    .shotgun_fire,
    .shotgun_reload,
    .autorifle_fire,
    .autorifle_reload,
    .gauss_fire,
    .hrpm_fire,
    .shock_fire,
    .plasmaminigun_fire,
    .plasmashotgun_fire,
    .pulse_fire,
    .flamer_fire_01,
    .flamer_fire_02,
    .shock_reload,
    .shock_fire_alt,
    .shockminigun_fire,
    .rocket_fire,
    .rocketmini_fire,
    .autorifle_reload_alt,
    .bullet_hit_01,
    .bullet_hit_02,
    .bullet_hit_03,
    .bullet_hit_04,
    .bullet_hit_05,
    .bullet_hit_06,
    .shock_hit_01,
    .explosion_small,
    .explosion_medium,
    .explosion_large,
    .shockwave,
    .questhit,
    .ui_bonus,
    .ui_buttonclick,
    .ui_panelclick,
    .ui_levelup,
    .ui_typeclick_01,
    .ui_typeclick_02,
    .ui_typeenter,
    .ui_clink_01,
    .bloodspill_01,
    .bloodspill_02,
};

pub const specs = std.EnumArray(SfxId, SfxSpec).init(.{
    .trooper_inpain_01 = .{ .entry_name = "trooper_inPain_01.ogg" },
    .trooper_inpain_02 = .{ .entry_name = "trooper_inPain_02.ogg" },
    .trooper_inpain_03 = .{ .entry_name = "trooper_inPain_03.ogg" },
    .trooper_die_01 = .{ .entry_name = "trooper_die_01.ogg" },
    .trooper_die_02 = .{ .entry_name = "trooper_die_02.ogg" },
    .trooper_die_03 = .{ .entry_name = "trooper_die_03.ogg" },
    .zombie_die_01 = .{ .entry_name = "zombie_die_01.ogg" },
    .zombie_die_02 = .{ .entry_name = "zombie_die_02.ogg" },
    .zombie_die_03 = .{ .entry_name = "zombie_die_03.ogg" },
    .zombie_die_04 = .{ .entry_name = "zombie_die_04.ogg" },
    .zombie_attack_01 = .{ .entry_name = "zombie_attack_01.ogg" },
    .zombie_attack_02 = .{ .entry_name = "zombie_attack_02.ogg" },
    .alien_die_01 = .{ .entry_name = "alien_die_01.ogg" },
    .alien_die_02 = .{ .entry_name = "alien_die_02.ogg" },
    .alien_die_03 = .{ .entry_name = "alien_die_03.ogg" },
    .alien_die_04 = .{ .entry_name = "alien_die_04.ogg" },
    .alien_attack_01 = .{ .entry_name = "alien_attack_01.ogg" },
    .alien_attack_02 = .{ .entry_name = "alien_attack_02.ogg" },
    .lizard_die_01 = .{ .entry_name = "lizard_die_01.ogg" },
    .lizard_die_02 = .{ .entry_name = "lizard_die_02.ogg" },
    .lizard_die_03 = .{ .entry_name = "lizard_die_03.ogg" },
    .lizard_die_04 = .{ .entry_name = "lizard_die_04.ogg" },
    .lizard_attack_01 = .{ .entry_name = "lizard_attack_01.ogg" },
    .lizard_attack_02 = .{ .entry_name = "lizard_attack_02.ogg" },
    .spider_die_01 = .{ .entry_name = "spider_die_01.ogg" },
    .spider_die_02 = .{ .entry_name = "spider_die_02.ogg" },
    .spider_die_03 = .{ .entry_name = "spider_die_03.ogg" },
    .spider_die_04 = .{ .entry_name = "spider_die_04.ogg" },
    .spider_attack_01 = .{ .entry_name = "spider_attack_01.ogg" },
    .spider_attack_02 = .{ .entry_name = "spider_attack_02.ogg" },
    .pistol_fire = .{ .entry_name = "pistol_fire.ogg" },
    .pistol_reload = .{ .entry_name = "pistol_reload.ogg" },
    .shotgun_fire = .{ .entry_name = "shotgun_fire.ogg" },
    .shotgun_reload = .{ .entry_name = "shotgun_reload.ogg" },
    .autorifle_fire = .{ .entry_name = "autorifle_fire.ogg" },
    .autorifle_reload = .{ .entry_name = "autorifle_reload.ogg" },
    .gauss_fire = .{ .entry_name = "gauss_fire.ogg" },
    .hrpm_fire = .{ .entry_name = "hrpm_fire.ogg" },
    .shock_fire = .{ .entry_name = "shock_fire.ogg" },
    .plasmaminigun_fire = .{ .entry_name = "plasmaMinigun_fire.ogg" },
    .plasmashotgun_fire = .{ .entry_name = "plasmaShotgun_fire.ogg" },
    .pulse_fire = .{ .entry_name = "pulse_fire.ogg" },
    .flamer_fire_01 = .{ .entry_name = "flamer_fire_01.ogg" },
    .flamer_fire_02 = .{ .entry_name = "flamer_fire_02.ogg" },
    .shock_reload = .{ .entry_name = "shock_reload.ogg" },
    .shock_fire_alt = .{ .entry_name = "shock_fire.ogg" },
    .shockminigun_fire = .{ .entry_name = "shockMinigun_fire.ogg" },
    .rocket_fire = .{ .entry_name = "rocket_fire.ogg" },
    .rocketmini_fire = .{ .entry_name = "rocketmini_fire.ogg" },
    .autorifle_reload_alt = .{ .entry_name = "autorifle_reload.ogg" },
    .bullet_hit_01 = .{ .entry_name = "bullet_hit_01.ogg" },
    .bullet_hit_02 = .{ .entry_name = "bullet_hit_02.ogg" },
    .bullet_hit_03 = .{ .entry_name = "bullet_hit_03.ogg" },
    .bullet_hit_04 = .{ .entry_name = "bullet_hit_04.ogg" },
    .bullet_hit_05 = .{ .entry_name = "bullet_hit_05.ogg" },
    .bullet_hit_06 = .{ .entry_name = "bullet_hit_06.ogg" },
    .shock_hit_01 = .{ .entry_name = "shock_hit_01.ogg" },
    .explosion_small = .{ .entry_name = "explosion_small.ogg" },
    .explosion_medium = .{ .entry_name = "explosion_medium.ogg" },
    .explosion_large = .{ .entry_name = "explosion_large.ogg" },
    .shockwave = .{ .entry_name = "shockwave.ogg" },
    .questhit = .{ .entry_name = "questHit.ogg" },
    .ui_bonus = .{ .entry_name = "ui_bonus.ogg" },
    .ui_buttonclick = .{ .entry_name = "ui_buttonClick.ogg" },
    .ui_panelclick = .{ .entry_name = "ui_panelClick.ogg" },
    .ui_levelup = .{ .entry_name = "ui_levelUp.ogg" },
    .ui_typeclick_01 = .{ .entry_name = "ui_typeClick_01.ogg" },
    .ui_typeclick_02 = .{ .entry_name = "ui_typeClick_02.ogg" },
    .ui_typeenter = .{ .entry_name = "ui_typeEnter.ogg" },
    .ui_clink_01 = .{ .entry_name = "ui_clink_01.ogg" },
    .bloodspill_01 = .{ .entry_name = "bloodSpill_01.ogg" },
    .bloodspill_02 = .{ .entry_name = "bloodSpill_02.ogg" },
});

pub const bullet_hit_ids = [_]SfxId{
    .bullet_hit_01,
    .bullet_hit_02,
    .bullet_hit_03,
    .bullet_hit_04,
    .bullet_hit_05,
    .bullet_hit_06,
};

pub inline fn spec(sfx_id: SfxId) SfxSpec {
    return specs.get(sfx_id);
}

pub inline fn sfxIdForNativeId(sfx_id: i32) ?SfxId {
    if (sfx_id < 0 or sfx_id >= native_order.len) return null;
    return native_order[@intCast(sfx_id)];
}

test "native order mirrors declared spec count" {
    try std.testing.expectEqual(@as(usize, sfx_id_count), native_order.len);
    try std.testing.expectEqualStrings("shock_fire.ogg", spec(.shock_fire_alt).entry_name);
    try std.testing.expectEqual(SfxId.trooper_inpain_01, native_order[0]);
    try std.testing.expectEqual(SfxId.bloodspill_02, native_order[native_order.len - 1]);
}
