from __future__ import annotations

import sys
from pathlib import Path


DOC_PATH = Path("docs/creatures/spawning.md")

TEMPLATES_START_MARKER = "<!-- spawn-templates:start -->"
TEMPLATES_END_MARKER = "<!-- spawn-templates:end -->"

STATUS_START_MARKER = "<!-- spawn-status:start -->"
STATUS_END_MARKER = "<!-- spawn-status:end -->"


def _repo_import() -> None:
    # Add `src/` to sys.path so we can import `crimson.*` from the repo root.
    repo_root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(repo_root / "src"))


def _format_flags(flags: object | None) -> str:
    if flags is None:
        return ""
    # flags is an IntFlag; render as a single hex value (this matches existing docs style).
    return f"0x{int(flags):x}"


def _replace_block(text: str, *, start_marker: str, end_marker: str, replacement: str) -> str:
    if start_marker not in text or end_marker not in text:
        raise SystemExit(f"markers not found in {DOC_PATH}: {start_marker} .. {end_marker}")
    before, rest = text.split(start_marker, 1)
    _, after = rest.split(end_marker, 1)
    return f"{before}{start_marker}\n{replacement}{end_marker}{after}"


def _render_table() -> str:
    _repo_import()
    from crimson.creatures.spawn import SPAWN_TEMPLATES  # noqa: PLC0415

    lines = [
        "Generated by `uv run scripts/gen_spawn_templates.py`.",
        "",
        "| Spawn id (template_id) | Type id | Creature | Flags (creature_flags) | Anim note |",
        "| --- | --- | --- | --- | --- |",
    ]
    for entry in sorted(SPAWN_TEMPLATES, key=lambda t: t.spawn_id):
        type_id = "" if entry.type_id is None else str(int(entry.type_id))
        creature = "" if entry.creature is None else entry.creature
        anim_note = "" if entry.anim_note is None else entry.anim_note
        lines.append(
            f"| `0x{entry.spawn_id:x}` | `{type_id}` | `{creature}` | `{_format_flags(entry.flags)}` | {anim_note} |"
        )
    lines.append("")
    return "\n".join(lines)


def _render_status_table() -> str:
    _repo_import()
    from crimson.creatures.spawn import SPAWN_TEMPLATES  # noqa: PLC0415

    lines = [
        "Generated by `uv run scripts/gen_spawn_templates.py`.",
        "",
        "| Spawn id | Creature | Ported | Verified |",
        "| --- | --- | --- | --- |",
    ]
    for entry in sorted(SPAWN_TEMPLATES, key=lambda t: t.spawn_id):
        creature = "" if entry.creature is None else entry.creature
        lines.append(f"| `0x{entry.spawn_id:x}` | `{creature}` | ✅ | ✅ |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    doc_text = DOC_PATH.read_text(encoding="utf-8")
    doc_text = _replace_block(
        doc_text,
        start_marker=TEMPLATES_START_MARKER,
        end_marker=TEMPLATES_END_MARKER,
        replacement=_render_table(),
    )
    doc_text = _replace_block(
        doc_text,
        start_marker=STATUS_START_MARKER,
        end_marker=STATUS_END_MARKER,
        replacement=_render_status_table(),
    )
    DOC_PATH.write_text(doc_text, encoding="utf-8")


if __name__ == "__main__":
    main()
