from __future__ import annotations

import re
from pathlib import Path


DECOMP_PATH = Path("analysis/ghidra/raw/crimsonland.exe_decompiled.c")
DOC_PATH = Path("docs/creature-struct.md")

START_MARKER = "<!-- spawn-templates:start -->"
END_MARKER = "<!-- spawn-templates:end -->"


def extract_function(text: str, label: str) -> str:
    idx = text.find(label)
    if idx == -1:
        raise SystemExit(f"function label not found: {label}")
    rest = text[idx + 1 :]
    m = re.search(r"/\\* FUN_[0-9A-Fa-f]+ @", rest)
    end = len(text) if m is None else idx + 1 + m.start()
    return text[idx:end]


def build_case_map(block: str) -> dict[str, dict[str, str | None]]:
    case_re = re.compile(r"\bif \(param_1 == ([^\)]+)\)")
    assign_type_re = re.compile(r"\(\&DAT_0049bfa4\)\[iVar4 \* 0x26\] = ([^;]+);")
    assign_flags_re = re.compile(r"\*\(undefined4 \*\)\(\&DAT_0049bfc4 \+ iVar8\) = ([^;]+);")

    cases: dict[str, dict[str, list[str]]] = {}
    pending: str | None = None
    active: list[tuple[str, int]] = []
    depth = 0

    for line in block.splitlines():
        stripped = line.strip()
        m = case_re.search(stripped)
        if m:
            val = m.group(1).strip()
            if "{" in stripped:
                active.append((val, depth + 1))
            else:
                pending = val
        if pending and "{" in stripped:
            active.append((pending, depth + 1))
            pending = None

        if active:
            mt = assign_type_re.search(stripped)
            if mt:
                val_assign = mt.group(1).strip()
                for case_val, _ in active:
                    entry = cases.setdefault(case_val, {"type": [], "flags": []})
                    entry["type"].append(val_assign)
            mf = assign_flags_re.search(stripped)
            if mf:
                val_assign = mf.group(1).strip()
                for case_val, _ in active:
                    entry = cases.setdefault(case_val, {"type": [], "flags": []})
                    entry["flags"].append(val_assign)

        depth += stripped.count("{")
        depth -= stripped.count("}")
        active = [(v, d) for (v, d) in active if depth >= d]

    summary: dict[str, dict[str, str | None]] = {}
    for key, val in cases.items():
        summary[key] = {
            "type": val["type"][-1] if val["type"] else None,
            "flags": val["flags"][-1] if val["flags"] else None,
        }
    return summary


def format_table(case_map: dict[str, dict[str, str | None]]) -> str:
    anim_notes = {
        "4": "short strip (ping‑pong)",
        "0x10": "alt strip (+0x20)",
        "0x44": "long strip (`0x40` overrides `0x4`)",
    }

    def sort_key(val: str) -> int:
        try:
            return int(val, 0)
        except ValueError:
            return 1_000_000

    lines = [
        "Generated by `uv run python scripts/gen_spawn_templates.py`.",
        "",
        "| Spawn id (param_1) | Type id | Flags (bfc4) | Anim note |",
        "| --- | --- | --- | --- |",
    ]

    for key in sorted(case_map, key=sort_key):
        entry = case_map[key]
        try:
            key_disp = hex(int(key, 0))
        except ValueError:
            key_disp = key
        type_id = entry["type"] or ""
        flags = entry["flags"] or ""
        note = anim_notes.get(flags, "")
        lines.append(f"| `{key_disp}` | `{type_id}` | `{flags}` | {note} |")

    lines.append("")
    lines.append("")
    return "\n".join(lines)


def replace_block(text: str, replacement: str) -> str:
    if START_MARKER not in text or END_MARKER not in text:
        raise SystemExit("spawn template markers not found in docs/creature-struct.md")
    before, rest = text.split(START_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    return f"{before}{START_MARKER}\n{replacement}{END_MARKER}{after}"


def main() -> int:
    text = DECOMP_PATH.read_text(encoding="utf-8")
    block = extract_function(text, "/* FUN_00430af0")
    case_map = build_case_map(block)
    replacement = format_table(case_map)

    doc = DOC_PATH.read_text(encoding="utf-8")
    updated = replace_block(doc, replacement)
    DOC_PATH.write_text(updated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
