IMAGE=grim.dll
FUNCTION=0x1001df16
END=0x1001df31
COMPILER=msvc7.0
SYMBOL=grim_jpeg_error_exit
SOURCE=../../shared/grim_jpeg_source_helpers.cpp
NOTE=ijg-error-exit
CFLAGS="/O1 /G6 /W3 /GR- /MD"
REFERENCE_ALIASES='grim_jpeg_destroy_source:d3dx_jpeg_destroy'
