IMAGE=grim.dll
FUNCTION=d3dx_jpeg_init_merged_upsampler
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\jdmerge.obj'
REFERENCE_ALIASES='?start_pass_merged_upsample@D3DX@@YAXPAUjpeg_decompress_struct@1@@Z:d3dx_jpeg_start_pass_merged_upsample,?merged_2v_upsample@D3DX@@YAXPAUjpeg_decompress_struct@1@PAPAPAEPAIIPAPAE2I@Z:d3dx_jpeg_merged_2v_upsample,?h2v2_merged_upsample@D3DX@@YAXPAUjpeg_decompress_struct@1@PAPAPAEIPAPAE@Z:d3dx_jpeg_h2v2_merged_upsample,?merged_1v_upsample@D3DX@@YAXPAUjpeg_decompress_struct@1@PAPAPAEPAIIPAPAE2I@Z:d3dx_jpeg_merged_1v_upsample,?h2v1_merged_upsample@D3DX@@YAXPAUjpeg_decompress_struct@1@PAPAPAEIPAPAE@Z:d3dx_jpeg_h2v1_merged_upsample,?build_ycc_rgb_table@D3DX@@YAXPAUjpeg_decompress_struct@1@@Z:d3dx_jpeg_build_merged_ycc_rgb_table'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?jinit_merged_upsampler@D3DX@@YAXPAUjpeg_decompress_struct@1@@Z'
NOTE=directx-8.1-archive-d3dx-jpeg-init-merged-upsampler
