IMAGE=grim.dll
FUNCTION=0x10032110
COMPILER=msvc7.0
SYMBOL=grim_jpeg_merged_1v_upsample
SOURCE=../../shared/grim_jpeg_source_helpers.cpp
NOTE=ijg-merged-one-row-upsample
CFLAGS="/O1 /G6 /W3 /GR- /MD"
