IMAGE=crimsonland.exe
FUNCTION=mod_api_gfx_printf
SYMBOL=?mod_api_gfx_printf@mod_api_cpp_t@@UAAXMMPADZZ
SOURCE=../../../../decomp/1.9/crimsonland/mods/mod_api_gfx_printf.cpp
NOTE=mod-api-graphics-formatted-text
