IMAGE=grim.dll
FUNCTION=0x10041da0
COMPILER=msvc7.0
SYMBOL=grim_jpeg_start_pass_upsample
SOURCE=../../shared/grim_jpeg_source_helpers.cpp
NOTE=jaz-ijg-start-pass-upsample
CFLAGS="/O1 /G6 /W3 /GR- /MD"
