IMAGE=crimsonland.exe
FUNCTION=mod_api_sfx_play_sample
SYMBOL=?mod_api_sfx_play_sample@mod_api_cpp_t@@UAEXHMM@Z
SOURCE=../../../../decomp/1.9/crimsonland/mods/mod_api_sfx_play_sample.cpp
NOTE=mod-api-audio-sample-play
