IMAGE=grim.dll
FUNCTION=grim_jpeg_alloc_quant_table
SYMBOL=jpeg_alloc_quant_table
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jcomapi.c
NOTE=ijg-6a-stock-alloc-quant-table
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
