IMAGE=grim.dll
FUNCTION=grim_jpeg_do_barray_io
SYMBOL=do_barray_io
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jmemmgr.c
NOTE=ijg-6a-stock-memory-block-array-io
CFLAGS='/O2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
