IMAGE=grim.dll
FUNCTION=d3dx_blt_box_2d_a8
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\cd3dxblt.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?BltBox2D_A8@CD3DXBlt@@IAEJXZ'
NOTE=directx-8.1-archive-blt-box-a8
