IMAGE=grim.dll
FUNCTION=zlib_inflate_trees_dynamic
SYMBOL=inflate_trees_dynamic
SOURCE=../../../../third_party/sources/zlib-1.1.3/inftrees.c
NOTE=zlib-1.1.3-stock-inflate-trees-dynamic
CFLAGS='/O2 /GB /W3 /MD'
REFERENCE_ALIASES='huft_build:zlib_huft_build,cplens:zlib_cplens,cplext:zlib_cplext,cpdist:zlib_cpdist,cpdext:zlib_cpdext'
