IMAGE=grim.dll
FUNCTION=grim_pixel_format_scalar_deleting_destroy_dxt_base
SYMBOL='??_Ggrim_pixel_format_dxt_t@@UAEPAXI@Z'
SOURCE=scratch.cpp
COMPILER=msvc6.5pp
CFLAGS="/O1 /Oi /G6 /W3 /GR- /GX"
REFERENCE_ALIASES='??1grim_pixel_format_dxt_t@@UAE@XZ:grim_pixel_format_destroy_dxt'
NOTE=grim-dxt-base-scalar-deleting-destructor
