IMAGE=grim.dll
FUNCTION=grim_jaz_jpeg_output_pass_setup
SYMBOL=output_pass_setup
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdapistd.c
NOTE=ijg-6a-stock-output-pass-setup
CFLAGS='/O2 /GB /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
