#include "crimsonland_gameplay.h"

extern "C" {
extern int credits_secret_line_base_index;
extern char s_empty_string[];
extern char credits_name_ville_m[];
extern char credits_name_petri_j[];
extern char credits_name_valtteri_pihlajam[];

void credits_line_set(int index, char *text, int flags);
}

extern "C" void credits_build_lines(void)
{
    credits_line_set(0x00, s_empty_string, 0);
    credits_line_set(0x01, "Crimsonland", 1);
    credits_line_set(0x02, s_empty_string, 0);
    credits_line_set(0x03, s_empty_string, 0);
    credits_line_set(0x04, "Game Design:", 1);
    credits_line_set(0x05, "Tero Alatalo", 0);
    credits_line_set(0x06, s_empty_string, 0);
    credits_line_set(0x07, "Programming:", 1);
    credits_line_set(0x08, "Tero Alatalo", 0);
    credits_line_set(0x09, s_empty_string, 0);
    credits_line_set(0x0a, "Producer:", 1);
    credits_line_set(0x0b, "Zach Young", 0);
    credits_line_set(0x0c, s_empty_string, 0);
    credits_line_set(0x0d, "2D Art:", 1);
    credits_line_set(0x0e, "Tero Alatalo", 0);
    credits_line_set(0x0f, s_empty_string, 0);
    credits_line_set(0x10, "3D Modelling:", 1);
    credits_line_set(0x11, "Tero Alatalo", 0);
    credits_line_set(0x12, "Timo Palonen", 0);
    credits_line_set(0x13, s_empty_string, 0);
    credits_line_set(0x14, "Music:", 1);
    credits_line_set(0x15, credits_name_valtteri_pihlajam, 0);
    credits_line_set(0x16, "Ville Eriksson", 0);
    credits_line_set(0x17, s_empty_string, 0);
    credits_line_set(0x18, "Sound Effects:", 1);
    credits_line_set(0x19, "Ion Hardie", 0);
    credits_line_set(0x1a, "Tero Alatalo", 0);
    credits_line_set(0x1b, credits_name_valtteri_pihlajam, 0);
    credits_line_set(0x1c, "Ville Eriksson", 0);
    credits_line_set(0x1d, s_empty_string, 0);
    credits_line_set(0x1e, "Manual:", 1);
    credits_line_set(0x1f, "Miikka Kulmala", 0);
    credits_line_set(0x20, "Zach Young", 0);
    credits_line_set(0x21, s_empty_string, 0);
    credits_line_set(0x22, "Special thanks to:", 1);
    credits_line_set(0x23, credits_name_petri_j, 0);
    credits_line_set(0x24, "Peter Hajba / Remedy", 0);
    credits_line_set(0x25, s_empty_string, 0);
    credits_line_set(0x26, "Play testers:", 1);
    credits_line_set(0x27, "Avraham Petrosyan", 0);
    credits_line_set(0x28, "Bryce Baker", 0);
    credits_line_set(0x29, "Dan Ruskin", 0);
    credits_line_set(0x2a, "Dirk Bunk", 0);
    credits_line_set(0x2b, "Eric Dallaire", 0);
    credits_line_set(0x2c, "Erik Van Pelt", 0);
    credits_line_set(0x2d, "Ernie Ramirez", 0);
    credits_line_set(0x2e, "Ion Hardie", 0);
    credits_line_set(0x2f, "James C. Smith", 0);
    credits_line_set(0x30, "Jarkko Forsbacka", 0);
    credits_line_set(0x31, "Jeff McAteer", 0);
    credits_line_set(0x32, "Juha Alatalo", 0);
    credits_line_set(0x33, "Kalle Hahl", 0);
    credits_line_set(0x34, "Lars Brubaker", 0);
    credits_line_set(0x35, "Lee Cooper", 0);
    credits_line_set(0x36, "Markus Lassila", 0);
    credits_line_set(0x37, "Matti Alanen", 0);
    credits_line_set(0x38, "Miikka Kulmala", 0);
    credits_line_set(0x39, "Mika Alatalo", 0);
    credits_line_set(0x3a, "Mike Colonnese", 0);
    credits_line_set(0x3b, "Simon Hallam", 0);
    credits_line_set(0x3c, "Toni Nurminen", 0);
    credits_line_set(0x3d, credits_name_valtteri_pihlajam, 0);
    credits_line_set(0x3e, "Ville Eriksson", 0);
    credits_line_set(0x3f, credits_name_ville_m, 0);
    credits_line_set(0x40, "Zach Young", 0);
    credits_line_set(0x41, s_empty_string, 0);

    credits_line_set(0x42, "Greeting to:", 0);
    credits_line_set(0x42, "Chaos^", 0);
    credits_line_set(0x42, "Matricks", 0);
    credits_line_set(0x42, "Muzzy", 0);
    credits_line_set(0x42, s_empty_string, 0);

    credits_line_set(0x43, s_empty_string, 0);
    credits_line_set(0x44, "2003 (c) 10tons entertainment", 0);
    credits_line_set(0x45, "10tons logo by", 0);
    credits_line_set(0x46, "Pasi Heinonen", 0);
    credits_line_set(0x47, s_empty_string, 0);
    credits_line_set(0x48, s_empty_string, 0);
    credits_line_set(0x49, s_empty_string, 0);
    credits_line_set(0x4a, "Uses Vorbis Audio Decompression", 0);
    credits_line_set(0x4b, "2003 (c) Xiph.Org Foundation", 0);
    credits_line_set(0x4c, "(see vorbis.txt)", 0);
    credits_line_set(0x4d, s_empty_string, 0);
    credits_line_set(0x4e, s_empty_string, 0);
    credits_line_set(0x4f, s_empty_string, 0);
    credits_line_set(0x50, s_empty_string, 0);
    credits_line_set(0x51, s_empty_string, 0);
    credits_line_set(0x52, s_empty_string, 0);
    credits_line_set(0x53, s_empty_string, 0);

    credits_secret_line_base_index = 0x54;
    credits_line_set(0x54, s_empty_string, 0);
    credits_line_set(0x55, s_empty_string, 0);
    credits_line_set(0x56, s_empty_string, 0);
    credits_line_set(0x57, "You can stop watching now.", 0);
    credits_line_set(0x58, s_empty_string, 0);
    credits_line_set(0x59, s_empty_string, 0);
    credits_line_set(0x5a, s_empty_string, 0);
    credits_line_set(0x5b, s_empty_string, 0);
    credits_line_set(0x5c, s_empty_string, 0);
    credits_line_set(0x5d, s_empty_string, 0);
    credits_line_set(0x5e, s_empty_string, 0);
    credits_line_set(0x5f, s_empty_string, 0);
    credits_line_set(0x60, s_empty_string, 0);
    credits_line_set(0x61, s_empty_string, 0);
    credits_line_set(0x62, s_empty_string, 0);
    credits_line_set(0x63, s_empty_string, 0);
    credits_line_set(0x64, s_empty_string, 0);
    credits_line_set(0x65, s_empty_string, 0);
    credits_line_set(0x66, s_empty_string, 0);
    credits_line_set(0x67, s_empty_string, 0);
    credits_line_set(0x68, s_empty_string, 0);
    credits_line_set(0x69, s_empty_string, 0);
    credits_line_set(0x6a, s_empty_string, 0);
    credits_line_set(0x6b, s_empty_string, 0);
    credits_line_set(0x6c, s_empty_string, 0);
    credits_line_set(0x6d, s_empty_string, 0);
    credits_line_set(0x6e, s_empty_string, 0);
    credits_line_set(0x6f, s_empty_string, 0);
    credits_line_set(0x70, s_empty_string, 0);
    credits_line_set(0x71, s_empty_string, 0);
    credits_line_set(0x72, s_empty_string, 0);
    credits_line_set(0x73, s_empty_string, 0);
    credits_line_set(0x74, s_empty_string, 0);
    credits_line_set(0x75, s_empty_string, 0);
    credits_line_set(0x76, s_empty_string, 0);
    credits_line_set(0x77, "Click the ones with the round ones!", 0);
    credits_line_set(0x78, "(and be patient!)", 0);
    credits_line_set(0x79, s_empty_string, 0);
    credits_line_set(0x7a, s_empty_string, 0);
    credits_line_set(0x7b, s_empty_string, 0);
    credits_line_set(0x7c, s_empty_string, 0);
    credits_line_set(0x7d, s_empty_string, 0);
}
