IMAGE=grim.dll
FUNCTION=grim_jpeg_null_convert
SYMBOL=null_convert
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdcolor.c
NOTE=ijg-6a-stock-null-color-converter
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
