IMAGE=grim.dll
FUNCTION=zlib_inflate_codes_free
SYMBOL=inflate_codes_free
SOURCE=../../../../third_party/sources/zlib-1.1.3/infcodes.c
NOTE=zlib-1.1.3-stock-inflate-codes-free
CFLAGS='/O2 /GB /W3 /MD'
