IMAGE=grim.dll
FUNCTION=0x10032d2e
COMPILER=msvc7.0
SYMBOL=grim_jpeg_find_best_colors
SOURCE=../../shared/grim_jpeg_quant2_source.c
NOTE=ijg-two-pass-inverse-map-nearest-color-search
CFLAGS="/O1 /G6 /W3 /GR- /MD"
