IMAGE=grim.dll
FUNCTION=grim_jpeg_post_process_2pass
SYMBOL=post_process_2pass
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdpostct.c
NOTE=ijg-6a-stock-second-pass-decompression-quantization-postprocessor
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
