IMAGE=grim.dll
FUNCTION=0x1001e016
COMPILER=msvc7.0
SYMBOL=grim_jpeg_reset_error_manager
SOURCE=../../shared/grim_jpeg_source_callbacks.cpp
NOTE=jpeg-reset-error-manager
CFLAGS="/O1 /G6 /W3 /GR- /MD"
