IMAGE=grim.dll
FUNCTION=d3dx_image_load_png
ARCHIVE=../../../native/providers/build/directx-8.1/d3dx8.lib
ARCHIVE_MEMBER='obj\i386\cd3dximage.obj'
ARCHIVE_SHA256=39a8e21889a7c1f0b966f04a9e7d392de14ddebb3e091dfa1e5ce3e19564fc28
SYMBOL='?LoadPNG@CD3DXImage@@AAEJPBXK@Z'
REFERENCE_ALIASES='?d3dx_png_warning_fn@@YAXPAUpng_struct_def@D3DX@@PBD@Z:grim_jpeg_source_noop,?d3dx_png_error_fn@@YAXPAUpng_struct_def@D3DX@@PBD@Z:grim_png_error_longjmp,?d3dx_png_read_fn@@YAXPAUpng_struct_def@D3DX@@PAEI@Z:d3dx_png_read_fn,?png_set_gray_1_2_4_to_8@D3DX@@YAXPAUpng_struct_def@1@@Z:d3dx_png_set_expand,?png_set_tRNS_to_alpha@D3DX@@YAXPAUpng_struct_def@1@@Z:d3dx_png_set_expand'
NOTE=directx-8.1-archive-cd3dximage-load-png
