IMAGE=grim.dll
FUNCTION=grim_pixel_format_write_yuv_cache
SYMBOL='?write_pixel@grim_pixel_format_yuv_t@@UAEXIIPAM@Z'
SOURCE=scratch.cpp
COMPILER=msvc6.5pp
CFLAGS="/O1 /Oi /G6 /W3 /GR-"
NOTE=grim-yuv-cache-write
REFERENCE_ALIASES='?convert_vertex_space@grim_pixel_format_t@@IAEPAMPAM@Z:grim_convert_vertex_space,?load_yuv_cache@grim_pixel_format_yuv_t@@IAEHIIH@Z:grim_pixel_format_load_yuv_cache'
