IMAGE=grim.dll
FUNCTION=d3dx_jpeg_init_d_coef_controller
COMPILER=msvc7.0
SYMBOL=jinit_d_coef_controller
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdcoefct.c
NOTE=ijg-6a-d3dx-coefficient-controller-initializer
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='start_input_pass:d3dx_jpeg_start_coefficient_input_pass,start_output_pass:d3dx_jpeg_start_coefficient_output_pass,consume_data:d3dx_jpeg_consume_data,decompress_data:d3dx_jpeg_decompress_data,dummy_consume_data:d3dx_jpeg_dummy_consume_data,decompress_onepass:d3dx_jpeg_decompress_onepass,jround_up:jround_up'
