IMAGE=grim.dll
FUNCTION=d3dx_jpeg_dummy_consume_data
COMPILER=msvc7.0
SYMBOL=dummy_consume_data
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdcoefct.c
NOTE=ijg-6a-d3dx-suspended-coefficient-consumer
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
