IMAGE=grim.dll
FUNCTION=grim_jpeg_sep_upsample
SYMBOL=sep_upsample
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdsample.c
NOTE=ijg-6a-stock-separate-upsampler
CFLAGS='/O2 /Ob2 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
