IMAGE=grim.dll
FUNCTION=0x100254cd
COMPILER=msvc7.0
SYMBOL=png_handle_gAMA
SOURCE=../../../../third_party/sources/libpng-1.0.5/pngrutil.c
NOTE=libpng-1.0.5-gama-handler
CFLAGS='/O1 /Oi /G6 /W3 /MD /DPNG_NO_READ_USER_TRANSFORM /DPNG_NO_WRITE_USER_TRANSFORM /DPNG_NO_READ_GRAY_TO_RGB /DPNG_NO_READ_BACKGROUND /DPNG_NO_READ_bKGD /DPNG_NO_READ_sBIT /DPNG_NO_READ_cHRM /DPNG_NO_CONSOLE_IO /DPNG_NO_READ_PACKSWAP'
