IMAGE=grim.dll
FUNCTION=d3dx_jpeg_init_upsampler
COMPILER=msvc6.5pp
SYMBOL=jinit_upsampler
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdsample.c
NOTE=ijg-6a-d3dx-separate-upsampler-init
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
REFERENCE_ALIASES='start_pass_upsample:d3dx_jpeg_start_pass_upsample,sep_upsample:d3dx_jpeg_sep_upsample,fullsize_upsample:d3dx_jpeg_fullsize_upsample,noop_upsample:d3dx_jpeg_noop_upsample,int_upsample:d3dx_jpeg_int_upsample,h2v1_upsample:d3dx_jpeg_h2v1_upsample,h2v2_upsample:d3dx_jpeg_h2v2_upsample,h2v1_fancy_upsample:d3dx_jpeg_h2v1_fancy_upsample,h2v2_fancy_upsample:d3dx_jpeg_h2v2_fancy_upsample'
