IMAGE=grim.dll
FUNCTION=d3dx_jpeg_start_pass_upsample
COMPILER=msvc7.0
SYMBOL=start_pass_upsample
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdsample.c
NOTE=ijg-6a-d3dx-upsampler-pass-init
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
