IMAGE=grim.dll
FUNCTION=grim_pixel_format_ctor_dxt3
SYMBOL='??0grim_pixel_format_dxt3_t@@QAE@PAI@Z'
SOURCE=scratch.cpp
COMPILER=msvc6.5pp
CFLAGS="/O1 /Oi /G6 /W3 /GR-"
REFERENCE_ALIASES='??0grim_pixel_format_dxt_t@@QAE@PAI@Z:grim_pixel_format_init_dxt,??_7grim_pixel_format_dxt3_t@@6B@:grim_pixel_format_vtable_dxt3'
NOTE=grim-pixel-format-dxt3-constructor
